export const SYNTHETIC_BUDGET_BASIS_REFERENCE_TITLE =
  'SYNTHETIC BUDGET-BASIS MISMATCH REFERENCE — NOT PRODUCTION APPROVED' as const;

export const SYNTHETIC_BUDGET_BASIS_REFERENCE_DISCLAIMER =
  'MANUAL DEV-ONLY REFERENCE — PRE-AUTHORED SOURCE COPY ONLY' as const;

export const SYNTHETIC_BUDGET_BASIS_REFERENCE_SCOPE_LINE =
  'NO RENT/BUDGET COMPARISON EXECUTED' as const;

export const SYNTHETIC_BUDGET_BASIS_REFERENCE_REGIONS_IN_ORDER = [
  'SOURCE AND STATUS BOUNDARY',
  'PRE-AUTHORED 2 × 2 BASIS REFERENCE',
  'MISMATCH — UNKNOWN AND CALCULATION BLOCKED',
  'INDEPENDENT NUMERIC, RUNTIME AND QUALIFICATION BOUNDARIES',
  'NON-COMPUTATION RESULT'
] as const;

export const SYNTHETIC_BUDGET_BASIS_SOURCE_BOUNDARY = [
  'FEATURES 3 AND 4: budget_fit AND rent_rate_fit — QUALITATIVE BASIS-MISMATCH RULE ONLY',
  'SOURCE: XFR-D-013 v1.0 — APPROVED QUALITATIVE MISMATCH RULE',
  'DESIGN-TIME registry_readiness = READY_AS_CANDIDATE_ONLY — NO ACTIVE SCORED OR RUNTIME FeatureValue',
  'EXACT UNKNOWN RUNTIME REPRESENTATION AND FUTURE NUMERIC OPERATING-EXPENSE FIELD REMAIN OPEN',
  'automatic_ineligible_allowed = NO — ALL THREE GOVERNANCE GATES REMAIN BLOCKED'
] as const;

export const SYNTHETIC_BUDGET_BASIS_CASES = [
  {
    propertyOperatingExpensesIncluded: 'true',
    requestBudgetIncludesOperatingExpenses: 'true',
    basisStatus: 'BASIS_ALIGNED',
    boundary: 'ORDINARY rent ≤ budget_max COMPARISON REMAINS GOVERNED ELSEWHERE — NO COMPARISON HERE',
    notAResult: 'NO AFFORDABILITY, COMPATIBILITY, FEATURE VALUE, PASS OR FAIL RESULT'
  },
  {
    propertyOperatingExpensesIncluded: 'false',
    requestBudgetIncludesOperatingExpenses: 'false',
    basisStatus: 'BASIS_ALIGNED',
    boundary: 'ORDINARY rent ≤ budget_max COMPARISON REMAINS GOVERNED ELSEWHERE — NO COMPARISON HERE',
    notAResult: 'NO AFFORDABILITY, COMPATIBILITY, FEATURE VALUE, PASS OR FAIL RESULT'
  },
  {
    propertyOperatingExpensesIncluded: 'true',
    requestBudgetIncludesOperatingExpenses: 'false',
    basisStatus: 'BASIS_MISMATCH',
    boundary: 'CANDIDATE value_state = UNKNOWN — CALCULATION BLOCKED',
    notAResult: 'NO PASS, FAIL, INCOMPATIBILITY, REJECTION OR INELIGIBLE'
  },
  {
    propertyOperatingExpensesIncluded: 'false',
    requestBudgetIncludesOperatingExpenses: 'true',
    basisStatus: 'BASIS_MISMATCH',
    boundary: 'CANDIDATE value_state = UNKNOWN — CALCULATION BLOCKED',
    notAResult: 'NO PASS, FAIL, INCOMPATIBILITY, REJECTION OR INELIGIBLE'
  }
] as const;

export const SYNTHETIC_BUDGET_BASIS_MISMATCH_BOUNDARY = [
  'BASIS MISMATCH IS FAIL-CLOSED ONLY BY BLOCKING THE CALCULATION AND PRESERVING CANDIDATE UNKNOWN',
  'UNKNOWN IS NOT A NEGATIVE FACT, FAILURE, INCOMPATIBILITY, REJECTION OR INELIGIBLE RESULT',
  'NO EXPENSE AMOUNT IS INVENTED OR ESTIMATED',
  'NO RENT/BUDGET OR EFFECTIVE-RATE COMPARISON IS EXECUTED'
] as const;

export const SYNTHETIC_BUDGET_BASIS_OPEN_BOUNDARIES = [
  'budget_fit REMAINS INDEPENDENT',
  'rent_rate_fit REMAINS INDEPENDENT',
  'XFR-D-003 EFFECTIVE-RATE NUMERIC, ROUNDING AND SERIALIZATION CONTRACT REMAINS INDEPENDENT AND OPEN',
  'MATCHING_QUALIFICATION_POLICY RUNTIME ROUTING AND OPERATIONAL CONSEQUENCES REMAIN INDEPENDENT AND OPEN',
  'EXACT RUNTIME REPRESENTATION OF UNKNOWN FOR THIS RULE REMAINS OPEN',
  'ANY FUTURE NUMERIC OPERATING-EXPENSE AMOUNT FIELD REMAINS OPEN',
  'PUBLIC API, EVENT, DATABASE, SCHEMA, CARRIER, REASON CODES AND EVIDENCE REMAIN OPEN',
  'NO AMOUNT, NUMERIC FIELD, FORMULA, THRESHOLD, ROUNDING, SERIALIZATION, RUNTIME ENUM OR EVALUATOR IS AUTHORIZED'
] as const;

export const SYNTHETIC_BUDGET_BASIS_TERMINAL_TOKEN =
  'SYNTHETIC_NO_BUDGET_BASIS_COMPARISON_EXECUTED' as const;

export const SYNTHETIC_BUDGET_BASIS_TERMINAL_LINE =
  'NO RENT/BUDGET COMPARISON EXECUTED — NO EXPENSE AMOUNT, EFFECTIVE RATE, FEATURE VALUE, PASS, FAIL, INELIGIBLE, SCORE, CONFIDENCE, QUALIFICATION, RISK, RANKING, RECOMMENDATION OR ROUTING OCCURRED' as const;
