export const SYNTHETIC_MATCHING_FLOW_CONSOLE_TITLE =
  'SYNTHETIC MATCHING FLOW CONSOLE — NOT PRODUCTION APPROVED' as const;

export const SYNTHETIC_MATCHING_FLOW_CONSOLE_SCENARIO =
  'SCENARIO: SYNTHETIC_MATCHING_FLOW_CONSOLE_A' as const;

export const SYNTHETIC_MATCHING_FLOW_CONSOLE_DISCLAIMER =
  'MANUAL DEV-ONLY REHEARSAL — NO DEAL EXECUTION' as const;

export const SYNTHETIC_MATCHING_FLOW_CONSOLE_NON_OCCURRENCE =
  'NO MATCH, SCORE, CONFIDENCE, QUALIFICATION, RISK, RANKING, CONTACT, DEAL OR OUTCOME OCCURRED' as const;

export const SYNTHETIC_MATCHING_FLOW_CONSOLE_STAGE_NODES = [
  {
    accessibleName: 'STAGE NODE 1 — TEST DEAL TOKEN',
    lines: ['TEST DEAL TOKEN — SYNTHETIC_TEST_DEAL_A']
  },
  {
    accessibleName: 'STAGE NODE 2 — CAMPAIGN PREVIEW',
    lines: [
      'CAMPAIGN PREVIEW — SYNTHETIC_CAMPAIGN_PREVIEW_A',
      'PREVIEW ONLY — NOT LAUNCHED'
    ]
  },
  {
    accessibleName: 'STAGE NODE 3 — FIXTURE PAIR',
    lines: [
      'SYNTHETIC_FIXTURE_PARTY_A + SYNTHETIC_FIXTURE_PARTY_B',
      'FIXTURE ONLY — NOT MATCHED OR RANKED'
    ]
  },
  {
    accessibleName: 'STAGE NODE 4 — SAFE PRESENTATION',
    lines: ['SAFE PRESENTATION — SYNTHETIC_SAFE_PRESENTATION_A']
  },
  {
    accessibleName: 'STAGE NODE 5 — HUMAN REHEARSAL DISPOSITION',
    lines: ['HUMAN REHEARSAL DISPOSITION REQUIRED']
  },
  {
    accessibleName: 'STAGE NODE 6 — NON-OCCURRENCE RESULT',
    lines: [
      'SYNTHETIC_NO_DEAL_EXECUTED',
      SYNTHETIC_MATCHING_FLOW_CONSOLE_NON_OCCURRENCE
    ]
  }
] as const;

export const SYNTHETIC_MATCHING_FLOW_CONSOLE_DISPOSITIONS = [
  'CONTINUE REHEARSAL',
  'HOLD REHEARSAL'
] as const;

export const SYNTHETIC_MATCHING_FLOW_CONSOLE_RESET = 'RESET' as const;

export type SyntheticMatchingFlowConsoleDisposition =
  (typeof SYNTHETIC_MATCHING_FLOW_CONSOLE_DISPOSITIONS)[number];
