export const G48_TITLE =
  'SYNTHETIC CRITICAL CONFLICTING-EVIDENCE QUALITATIVE-CRITICALITY REFERENCE — NOT PRODUCTION APPROVED' as const;

export const G48_DISCLAIMER =
  'MANUAL DEV-ONLY REFERENCE — OUTCOME-SENSITIVE CRITICALITY IS NOT NUMERIC THRESHOLD, CRITICAL-FIELD CATALOG OR RUNTIME CLASSIFIER APPROVAL' as const;

export const G48_SCOPE_LINE =
  'NO NUMERIC THRESHOLD, EXHAUSTIVE CRITICAL-FIELD CATALOG, SEVERITY SCALE, RUNTIME CLASSIFIER, POLICY OR RUNTIME USE SELECTED' as const;

export const G48_REGIONS = [
  'SOURCE AND STATUS BOUNDARY',
  'OUTCOME-SENSITIVE CRITICALITY BOUNDARY',
  'QUALIFICATION PRECEDENCE AND HUMAN-REVIEW BOUNDARY',
  'NONCRITICAL CONFLICT PRESERVATION AND NON-NEGATIVE BOUNDARY',
  'OPEN EXACT CONTENT',
  'NON-DECISION RESULT'
] as const;

export const G48_SOURCE_BOUNDARY = [
  'SOURCE DECISION: XFR-D-037 v1.0 — RESOLVED_QUALITATIVE_BOUNDARY',
  'SOURCE STATUS: APPROVED QUALITATIVE CONFLICT CRITICALITY — NO NUMERIC THRESHOLD APPROVED',
  'CANONICAL IDENTITY: MQP-10 → XFR-D-037 — PRIMARY_STANDALONE',
  'INVENTORY COUNTS: 102 SOURCE KEYS / 90 CANONICAL IDS — UNCHANGED; QUALIFICATION REGISTER REMAINS 20 ROWS',
  'APPROVED BOUNDARY ONLY: OUTCOME-SENSITIVE CRITICALITY, XFR-D-033 HUMAN-REVIEW PRECEDENCE, ALL-VERSION PRESERVATION, CONFIDENCE REDUCTION, NON-NEGATIVE TREATMENT AND NO AUTOMATIC REJECTION',
  'IMPLEMENTATION READINESS, SYNTHETIC ACCEPTANCE AND PRODUCTION LAUNCH REMAIN BLOCKED; PACKAGE GATE IMPACT IS NONE'
] as const;

export const G48_ROLE_BOUNDARY = [
  'QUALIFICATION SEMANTIC OWNER: Chief AI Architect + PRODUCT',
  'MANDATORY APPROVERS: LEGAL + DEVELOPMENT',
  'CONSULTED DOMAIN FUNCTION: AI — WITHOUT UNILATERAL APPROVAL AUTHORITY',
  'CHANGE CONTROL REQUIRES A NEW VERSIONED RECORD AGREED BY Chief AI Architect + PRODUCT + LEGAL + DEVELOPMENT WITH SUPERSEDES LINKAGE',
  'NO REVIEWER, TOOL, CODE, CI RESULT, COMMIT OR MERGE CAN CREATE A NUMERIC THRESHOLD, CATALOG OR CLASSIFIER AUTHORITY'
] as const;

export const G48_OUTCOME_CLASSES = [
  'ELIGIBILITY RESULT',
  'ANY OF THE FOUR QUALIFICATION RESULTS',
  'A HARD CONSTRAINT OR MANDATORY ARCHITECTURE SECTION 18.1 CONDITION',
  'A PROTECTED-ATTRIBUTE / PROXY, LAWFUL-BASIS, AUTHORITY OR OTHER LEGAL / RIGHTS BOUNDARY',
  'SAFE PRESENTATION OR SUBSEQUENT DISCLOSURE ADMISSIBILITY'
] as const;

export type G48BoundaryRow = { readonly matrixRow: string; readonly frozenBoundary: string };

export const G48_BOUNDARY_MATRIX: readonly G48BoundaryRow[] = [
  { matrixRow: 'PRIMARY_STANDALONE_IDENTITY_AND_RESOLVED_QUALITATIVE_BOUNDARY_PRESERVED_WITH_NUMERIC_THRESHOLD_AND_EXHAUSTIVE_CRITICAL_FIELD_CATALOG_OPEN', frozenBoundary: 'PRIMARY_STANDALONE_IDENTITY_AND_RESOLVED_QUALITATIVE_BOUNDARY_PRESERVED_WITH_NUMERIC_THRESHOLD_AND_EXHAUSTIVE_CRITICAL_FIELD_CATALOG_OPEN' },
  { matrixRow: 'QUALIFICATION_SEMANTIC_OWNER_CHIEF_AI_ARCHITECT_PLUS_PRODUCT_APPROVERS_LEGAL_PLUS_DEVELOPMENT_AND_AI_CONSULTED_WITHOUT_UNILATERAL_AUTHORITY', frozenBoundary: 'QUALIFICATION_SEMANTIC_OWNER_CHIEF_AI_ARCHITECT_PLUS_PRODUCT_APPROVERS_LEGAL_PLUS_DEVELOPMENT_AND_AI_CONSULTED_WITHOUT_UNILATERAL_AUTHORITY' },
  { matrixRow: 'A_CONFLICT_IS_CRITICAL_IF_SELECTING_ANY_PRESERVED_CONFLICTING_VERSION_CAN_CHANGE_THE_ELIGIBILITY_RESULT', frozenBoundary: 'A_CONFLICT_IS_CRITICAL_IF_SELECTING_ANY_PRESERVED_CONFLICTING_VERSION_CAN_CHANGE_THE_ELIGIBILITY_RESULT' },
  { matrixRow: 'A_CONFLICT_IS_CRITICAL_IF_SELECTING_ANY_PRESERVED_CONFLICTING_VERSION_CAN_CHANGE_ANY_OF_THE_FOUR_QUALIFICATION_RESULTS', frozenBoundary: 'A_CONFLICT_IS_CRITICAL_IF_SELECTING_ANY_PRESERVED_CONFLICTING_VERSION_CAN_CHANGE_ANY_OF_THE_FOUR_QUALIFICATION_RESULTS' },
  { matrixRow: 'A_CONFLICT_IS_CRITICAL_IF_SELECTING_ANY_PRESERVED_CONFLICTING_VERSION_CAN_CHANGE_A_HARD_CONSTRAINT_OR_MANDATORY_ARCHITECTURE_SECTION_18_1_CONDITION', frozenBoundary: 'A_CONFLICT_IS_CRITICAL_IF_SELECTING_ANY_PRESERVED_CONFLICTING_VERSION_CAN_CHANGE_A_HARD_CONSTRAINT_OR_MANDATORY_ARCHITECTURE_SECTION_18_1_CONDITION' },
  { matrixRow: 'A_CONFLICT_IS_CRITICAL_IF_SELECTING_ANY_PRESERVED_CONFLICTING_VERSION_CAN_CHANGE_A_PROTECTED_PROXY_LAWFUL_BASIS_AUTHORITY_OR_OTHER_LEGAL_RIGHTS_BOUNDARY', frozenBoundary: 'A_CONFLICT_IS_CRITICAL_IF_SELECTING_ANY_PRESERVED_CONFLICTING_VERSION_CAN_CHANGE_A_PROTECTED_PROXY_LAWFUL_BASIS_AUTHORITY_OR_OTHER_LEGAL_RIGHTS_BOUNDARY' },
  { matrixRow: 'A_CONFLICT_IS_CRITICAL_IF_SELECTING_ANY_PRESERVED_CONFLICTING_VERSION_CAN_CHANGE_SAFE_PRESENTATION_OR_SUBSEQUENT_DISCLOSURE_ADMISSIBILITY', frozenBoundary: 'A_CONFLICT_IS_CRITICAL_IF_SELECTING_ANY_PRESERVED_CONFLICTING_VERSION_CAN_CHANGE_SAFE_PRESENTATION_OR_SUBSEQUENT_DISCLOSURE_ADMISSIBILITY' },
  { matrixRow: 'A_CRITICAL_CONFLICT_REQUIRES_HUMAN_REVIEW_REQUIRED_SUBJECT_TO_XFR_D_033_PRECEDENCE_AND_DOES_NOT_OVERRIDE_CONFIRMED_INELIGIBILITY', frozenBoundary: 'A_CRITICAL_CONFLICT_REQUIRES_HUMAN_REVIEW_REQUIRED_SUBJECT_TO_XFR_D_033_PRECEDENCE_AND_DOES_NOT_OVERRIDE_CONFIRMED_INELIGIBILITY' },
  { matrixRow: 'A_NONCRITICAL_CONFLICT_PRESERVES_ALL_VERSIONS_AND_EVIDENCE_REFERENCES_REDUCES_CONFIDENCE_AND_IS_NOT_A_NEGATIVE_FACT_OR_AUTOMATIC_REJECTION', frozenBoundary: 'A_NONCRITICAL_CONFLICT_PRESERVES_ALL_VERSIONS_AND_EVIDENCE_REFERENCES_REDUCES_CONFIDENCE_AND_IS_NOT_A_NEGATIVE_FACT_OR_AUTOMATIC_REJECTION' },
  { matrixRow: 'A_NONCRITICAL_CONFLICT_CONTINUES_ONLY_UNDER_SEPARATELY_APPROVED_CONFIDENCE_COMPLETENESS_AND_VERIFICATION_RULES', frozenBoundary: 'A_NONCRITICAL_CONFLICT_CONTINUES_ONLY_UNDER_SEPARATELY_APPROVED_CONFIDENCE_COMPLETENESS_AND_VERIFICATION_RULES' },
  { matrixRow: 'NUMERIC_THRESHOLD_SEVERITY_SCALE_EXHAUSTIVE_CRITICAL_FIELD_CATALOG_RUNTIME_CLASSIFIER_SCHEMA_POLICY_DATA_PRODUCTION_RUNTIME_AND_IMPLEMENTATION_REMAIN_OPEN', frozenBoundary: 'NUMERIC_THRESHOLD_SEVERITY_SCALE_EXHAUSTIVE_CRITICAL_FIELD_CATALOG_RUNTIME_CLASSIFIER_SCHEMA_POLICY_DATA_PRODUCTION_RUNTIME_AND_IMPLEMENTATION_REMAIN_OPEN' },
  { matrixRow: 'GATE_IMPACT_NONE_AND_IMPLEMENTATION_READINESS_SYNTHETIC_ACCEPTANCE_AND_PRODUCTION_LAUNCH_REMAIN_BLOCKED', frozenBoundary: 'GATE_IMPACT_NONE_AND_IMPLEMENTATION_READINESS_SYNTHETIC_ACCEPTANCE_AND_PRODUCTION_LAUNCH_REMAIN_BLOCKED' }
] as const;

export const G48_CRITICALITY_BOUNDARY = [
  'CRITICALITY IS OUTCOME-SENSITIVE: SELECTING ANY PRESERVED CONFLICTING VERSION MUST BE CAPABLE OF CHANGING AT LEAST ONE APPROVED OUTCOME CLASS',
  'THE FIVE CLASSES ARE QUALITATIVE GOVERNANCE BOUNDARIES, NOT A FIELD CATALOG, SEVERITY SCALE, WEIGHTING MODEL OR CLASSIFIER FEATURE SET',
  'CRITICALITY DOES NOT SELECT ONE VERSION AS TRUTH AND DOES NOT ITSELF CREATE A LEGAL, ELIGIBILITY, QUALIFICATION OR DISCLOSURE VERDICT',
  'FIELD IMPORTANCE, SOURCE PRIORITY, COMPLETENESS, CONFIDENCE OR UI EMPHASIS CANNOT SUBSTITUTE FOR THE APPROVED OUTCOME-CHANGE TEST'
] as const;

export const G48_PRECEDENCE_BOUNDARY = [
  'A CRITICAL CONFLICT REQUIRES HUMAN_REVIEW_REQUIRED SUBJECT TO THE COMPLETE XFR-D-033 PRECEDENCE HIERARCHY',
  'CONFIRMED ELIGIBILITY INELIGIBLE WITH REQUIRED EVIDENCE RETAINS HIGHER PRECEDENCE AND IS NOT OVERRIDDEN',
  'PRECEDENCE SELECTS THE FINAL QUALIFICATION ROUTE BUT DOES NOT DELETE OTHER APPLICABLE CAUSES OR EVIDENCE REFERENCES',
  'A HUMAN-REVIEW DIRECTION IS NOT A QUEUE ITEM, REVIEWER APPOINTMENT, ACCESS GRANT, FACTUAL RESOLUTION, LEGAL VERDICT OR IMPLEMENTATION AUTHORITY',
  'SCORE, RANK, CONFIDENCE, BUSINESS URGENCY OR AGGREGATE EVIDENCE CANNOT COMPENSATE FOR A CRITICAL CONFLICT OR REQUIRED HUMAN REVIEW'
] as const;

export const G48_NONCRITICAL_BOUNDARY = [
  'EVERY NONCRITICAL CONFLICT STILL PRESERVES ALL CONFLICTING VERSIONS AND EVIDENCE REFERENCES',
  'A NONCRITICAL CONFLICT REDUCES CONFIDENCE UNDER A SEPARATELY APPROVED RULE',
  'A NONCRITICAL CONFLICT IS NOT A NEGATIVE FACT AND BY ITSELF CREATES NO AUTOMATIC REJECTION',
  'IT DOES NOT CREATE A HARD-CONSTRAINT FAILURE, INELIGIBLE, REJECTED_BY_MATCHING OR ADVERSE LEGAL FACT AND CREATES NO AUTOMATIC ROUTE',
  'FURTHER EVALUATION MAY USE ONLY SEPARATELY APPROVED CONFIDENCE, COMPLETENESS AND VERIFICATION RULES'
] as const;

export const G48_SURROGATE_GUARDRAILS = [
  'CONVENTIONAL SEVERITY SCORE, ORDINAL LABEL OR NUMERIC CUTOFF CANNOT SERVE AS A CRITICALITY SURROGATE',
  'FIELD IMPORTANCE, CRITICAL-DATA MEMBERSHIP OR EXHAUSTIVE FIELD LIST CANNOT BE INFERRED FROM THIS QUALITATIVE DEFINITION',
  'EVIDENCE STATUS, SOURCE PRIORITY, CONFIDENCE CUTOFF OR COMPLETENESS THRESHOLD CANNOT SERVE AS A SURROGATE',
  'UI LABEL, BUSINESS PRIORITY, PILOT KPI OR IMPLEMENTATION DEFAULT CANNOT SERVE AS A SURROGATE',
  'NO RUNTIME CLASSIFIER, COMPARISON PROCEDURE, FALLBACK OR HIDDEN DEFAULT IS APPROVED',
  'SYNTHETIC-ONLY EVIDENCE CREATES NO PRODUCTION CLASSIFIER, PRODUCTION-READINESS CLAIM OR RUNTIME PERMISSION'
] as const;

export const G48_OPEN_CONTENT = [
  'NUMERIC THRESHOLD, SEVERITY METRIC, SCALE, COMPARATOR, VALUE, UNIT, RANGE, PRECISION, ROUNDING AND TOLERANCE',
  'CRITICAL-FIELD CATALOG IDENTIFIERS, MEMBERSHIP, APPLICABILITY, SOURCE AUTHORITY, VERSIONING AND EXHAUSTIVENESS',
  'CONFLICT DETECTION, COMPARISON, NORMALIZATION, CLASSIFICATION AND EVIDENCE-COMPATIBILITY PROCEDURE',
  'OUTCOME-CHANGE CAPABILITY DETERMINATION, PROOF STANDARD AND UNCERTAINTY HANDLING',
  'MULTIPLE-CONFLICT AGGREGATION, ORDER, TIE, PRIMARY-CAUSE AND CASCADE BEHAVIOR',
  'CONFIDENCE REDUCTION FORMULA, AMOUNT, DIRECTION, FLOOR, AGGREGATION AND INTERACTION RULE',
  'REVIEWER APPOINTMENT, RBAC, QUORUM, FOUR-EYES, CONFLICT CHECK, APPEAL, QUEUE, SLA AND VERDICT WORKFLOW',
  'QUALIFICATION POLICY, DATA CONTRACTS, MANIFEST, DATASET, EVALUATION, PRODUCTION, SCHEMA, API, DB, EVENT, CARRIER, OBSERVABILITY, RUNTIME, IMPLEMENTATION, RELEASE AND GATES'
] as const;

export const G48_INDEPENDENT_BOUNDARIES = [
  'XFR-D-033 RETAINS QUALITATIVE PRECEDENCE AUTHORITY AND XFR-D-040 RETAINS ALL-CAUSE / PRIMARY-REASON AUTHORITY',
  'XFR-D-038 STALE SEMANTICS, XFR-D-041 HUMAN-REVIEW QUEUE/AUTHORITY AND XFR-D-043 VERSION COMPATIBILITY REMAIN INDEPENDENT',
  'XFR-D-034, XFR-D-035, XFR-D-036 AND XFR-D-045 EVIDENCE BOUNDARIES REMAIN INDEPENDENT',
  'XFR-D-044 SAFE-PRESENTATION READ-ONLY CONSUMPTION AND APPLICABLE LEGAL / DISCLOSURE DECISIONS REMAIN INDEPENDENT',
  'NO SIBLING BOUNDARY IS REOPENED, ABSORBED, SUPERSEDED OR APPROVED BY G48'
] as const;

export const G48_NON_DECISION_RESULT =
  'G48 NON-DECISION RESULT: NO NUMERIC THRESHOLD, SEVERITY METRIC, SCALE, COMPARATOR, VALUE, CRITICAL-FIELD CATALOG, FIELD MEMBERSHIP, CONFLICT CLASSIFIER, COMPARISON OR NORMALIZATION PROCEDURE, PROOF STANDARD, AGGREGATION, CONFIDENCE-REDUCTION FORMULA, REVIEWER WORKFLOW, POLICY, MANIFEST, DATASET, EVIDENCE VERDICT, ROUTE ALGORITHM, SCHEMA, API, DB, EVENT, CARRIER, PRODUCTION-DATA USE, RUNTIME, MONITORING, IMPLEMENTATION OR RELEASE IS SELECTED, CALCULATED OR APPROVED. XFR-D-037 v1.0 REMAINS RESOLVED_QUALITATIVE_BOUNDARY AND MQP-10 REMAINS PRIMARY_STANDALONE. GATE IMPACT IS NONE, AND ALL THREE GOVERNANCE GATES REMAIN BLOCKED.' as const;

export const G48_TERMINAL_TOKEN =
  'G48_SYNTHETIC_NO_NUMERIC_THRESHOLD_EXHAUSTIVE_CRITICAL_FIELD_CATALOG_SEVERITY_SCALE_RUNTIME_CLASSIFIER_POLICY_OR_IMPLEMENTATION_AUTHORITY_ESTABLISHED' as const;

export const G48_TERMINAL_LINE =
  'NO NUMERIC THRESHOLD, EXHAUSTIVE CRITICAL-FIELD CATALOG, SEVERITY SCALE, RUNTIME CLASSIFIER, POLICY, PRODUCTION, RUNTIME OR IMPLEMENTATION ACTION OCCURRED' as const;
