export const SYNTHETIC_DEAL_STORY_TOKENS = {
  scenario: 'SYNTHETIC_DEAL_STORY_A',
  user: 'SYNTHETIC_USER_A',
  need: 'SYNTHETIC_NEED_A',
  campaignPreview: 'SYNTHETIC_CAMPAIGN_PREVIEW_A',
  safePresentation: 'SYNTHETIC_SAFE_PRESENTATION_A',
  humanContinuation: 'SYNTHETIC_HUMAN_CONTINUATION_REQUIRED',
  outcome: 'SYNTHETIC_NO_DEAL_EXECUTED'
} as const;

export const SYNTHETIC_DEAL_STORY_PREFIX_LINES = [
  'SYNTHETIC DEAL STORY — NOT PRODUCTION APPROVED',
  `SCENARIO: ${SYNTHETIC_DEAL_STORY_TOKENS.scenario}`,
  `STEP 1 — ${SYNTHETIC_DEAL_STORY_TOKENS.user} / ${SYNTHETIC_DEAL_STORY_TOKENS.need}`,
  `STEP 2 — ${SYNTHETIC_DEAL_STORY_TOKENS.campaignPreview}`,
  `STEP 3 — ${SYNTHETIC_DEAL_STORY_TOKENS.safePresentation}`
] as const;

export const SYNTHETIC_DEAL_STORY_SUFFIX_LINES = [
  `STEP 4 — ${SYNTHETIC_DEAL_STORY_TOKENS.humanContinuation}`,
  `OUTCOME — ${SYNTHETIC_DEAL_STORY_TOKENS.outcome}`,
  'NO MATCH, SCORE, QUALIFICATION, RISK DECISION OR PRODUCTION APPROVAL OCCURRED'
] as const;
