export const SYNTHETIC_ENTRANCE_REQUIREMENT_REFERENCE_TITLE =
  'SYNTHETIC ENTRANCE-REQUIREMENT COMPATIBILITY REFERENCE — NOT PRODUCTION APPROVED' as const;

export const SYNTHETIC_ENTRANCE_REQUIREMENT_REFERENCE_DISCLAIMER =
  'MANUAL DEV-ONLY REFERENCE — PRE-AUTHORED SOURCE COPY ONLY' as const;

export const SYNTHETIC_ENTRANCE_REQUIREMENT_REFERENCE_SCOPE_LINE =
  'NO ENTRANCE-REQUIREMENT COMPARISON EXECUTED' as const;

export const SYNTHETIC_ENTRANCE_REQUIREMENT_REFERENCE_REGIONS_IN_ORDER = [
  'SOURCE AND STATUS BOUNDARY',
  'ENTRANCE AXES — DISTINCT ENUMS, NO PHYSICAL OR PURPOSE INFERENCE',
  'PRE-AUTHORED 5 × 4 COMPATIBILITY REFERENCE',
  'PREFERENCE, FAIL-CLOSED AND PROHIBITED INFERENCES',
  'NON-COMPUTATION RESULT'
] as const;

export const SYNTHETIC_ENTRANCE_PROPERTY_AXIS = [
  'separate_street',
  'separate_yard',
  'shared',
  'loading_only',
  'none'
] as const;

export const SYNTHETIC_ENTRANCE_REQUEST_AXIS = [
  'separate_required',
  'separate_preferred',
  'shared_allowed',
  'no_preference'
] as const;

export const SYNTHETIC_ENTRANCE_REQUIREMENT_MATRIX = [
  ['COMPATIBLE', 'COMPATIBLE', 'NEEDS_VERIFICATION', 'COMPATIBLE'],
  ['COMPATIBLE', 'COMPATIBLE', 'NEEDS_VERIFICATION', 'COMPATIBLE'],
  ['INCOMPATIBLE_CANDIDATE', 'COMPATIBLE', 'COMPATIBLE', 'COMPATIBLE'],
  ['NEEDS_VERIFICATION', 'COMPATIBLE', 'NEEDS_VERIFICATION', 'COMPATIBLE'],
  ['NEEDS_VERIFICATION', 'COMPATIBLE', 'NEEDS_VERIFICATION', 'COMPATIBLE']
] as const;

export const SYNTHETIC_ENTRANCE_SOURCE_BOUNDARY = [
  'FEATURE 8: entrance_requirement_fit — registry_readiness = BLOCKED_PENDING_DECISION',
  'SOURCE: XFR-D-001 v1.0 — APPROVED PARTIAL QUALITATIVE COMPATIBILITY — 6 OF 20 PAIRS REMAIN OPEN',
  'HUMAN-GOVERNANCE INTERPRETATION — NOT A SOURCE-NORMATIVE OR ACTIVE RUNTIME COMPATIBILITY RELATION',
  'required_evidence_level = BLOCKED_PENDING_DECISION — FINAL LEGAL VERDICT = NOT_APPROVED — automatic_ineligible_allowed = NO'
] as const;

export const SYNTHETIC_ENTRANCE_AXIS_BOUNDARIES = [
  'PROPERTY entrance_type AND TENANTREQUEST entrance_requirement ARE DISTINCT SOURCE ENUMS',
  'NO SEPARATE-COVERS-SHARED ORDERING OR COVERAGE INFERENCE',
  'NO PHYSICAL ENTRANCE PROPERTY INFERENCE',
  'NO LOADING_ONLY OR NONE PURPOSE SEMANTICS INFERENCE'
] as const;

export const SYNTHETIC_ENTRANCE_PREFERENCE_AND_FAIL_CLOSED_BOUNDARIES = [
  'separate_preferred IS A PREFERENCE, NOT A HARD REQUIREMENT',
  'HARD COMPATIBLE DOES NOT PROVE THE PREFERENCE IS SATISFIED',
  'UNMET-PREFERENCE DIAGNOSTIC REMAINS CONCEPT-LEVEL, SEPARATE FROM THE HARD RESULT, NON-ROUTING AND NOT A RUNTIME FIELD',
  'REQUEST entrance_requirement ABSENT — CANDIDATE value_state = NOT_APPLICABLE — NO COMPARISON',
  'REQUEST entrance_requirement PRESENT AND PROPERTY entrance_type ABSENT — CANDIDATE value_state = UNKNOWN — DISTINCT FROM EXPLICIT none — NO COMPATIBILITY VERDICT',
  'INCOMPATIBLE_CANDIDATE IS NOT PASS, FAIL, REJECTION OR AUTOMATIC INELIGIBLE',
  'NO FEATURE VALUE, SCORE, CONFIDENCE, QUALIFICATION, RISK, RANKING, RECOMMENDATION, ROUTING OR BUSINESS ACTION'
] as const;

export const SYNTHETIC_ENTRANCE_TERMINAL_TOKEN =
  'SYNTHETIC_NO_ENTRANCE_REQUIREMENT_COMPARISON_EXECUTED' as const;

export const SYNTHETIC_ENTRANCE_TERMINAL_LINE =
  'NO ENTRANCE-REQUIREMENT COMPARISON EXECUTED — NO FEATURE VALUE, PASS, FAIL, INELIGIBLE, SCORE, CONFIDENCE, QUALIFICATION, RISK, RANKING, RECOMMENDATION OR ROUTING OCCURRED' as const;
