export const G36_TITLE =
  'SYNTHETIC WEIGHT-POLICY QUALITATIVE GOVERNANCE REFERENCE — NOT PRODUCTION APPROVED' as const;

export const G36_DISCLAIMER =
  'MANUAL DEV-ONLY REFERENCE — QUALITATIVE WEIGHT-POLICY GOVERNANCE AND EVIDENCE BOUNDARY ONLY' as const;

export const G36_SCOPE_LINE =
  'NO WEIGHT, RATIO, FORMULA, NORMALIZATION, THRESHOLD, SEGMENT OVERRIDE, POLICY OR RUNTIME USE SELECTED' as const;

export const G36_REGIONS = [
  'SOURCE AND STATUS BOUNDARY',
  'WEIGHT-POLICY QUALITATIVE MATRIX',
  'ROLE AND ARTIFACT-OWNER SEPARATION',
  'PARAMETER-FAMILY, GLOBAL-BASELINE, SEGMENT-OVERRIDE AND HARD-CONSTRAINT BOUNDARY',
  'OPEN EXACT CONTENT',
  'NON-DECISION RESULT'
] as const;

export const G36_SOURCE_BOUNDARY = [
  'SOURCE DECISION: XFR-D-M5 v1.0 — PARTIALLY_RESOLVED_BOUNDARY',
  'CANONICAL MERGED IDENTITY: MSP-02 + MSP-03 → XFR-D-M5 — BOTH SOURCE KEYS REMAIN PRIMARY_MERGED_MEMBER',
  'INVENTORY COUNTS: 102 SOURCE KEYS / 90 CANONICAL IDS — UNCHANGED',
  'APPROVED BOUNDARY IS QUALITATIVE ONLY: ROLE SEPARATION; DISTINCT PARAMETER FAMILIES; GLOBAL-BASELINE VERSUS LAWFUL SEGMENT-OVERRIDE AUTHORITY; HARD-CONSTRAINT PRECEDENCE; AFFECTED-USE FAIL-CLOSED; IMMUTABLE EVIDENCE; HISTORICAL INTEGRITY; AND NO AUTOMATIC ACTION',
  'EVERY EXACT WEIGHT, RATIO, FORMULA, NORMALIZATION, THRESHOLD, SEGMENT, MEMBERSHIP, LAWFUL BASIS, DATASET, METRIC, STATISTIC, POLICY, PRODUCTION-DATA USE, SCHEMA, CARRIER, API, DB, EVENT, RUNTIME AND IMPLEMENTATION CONTENT REMAINS OPEN',
  'IMPLEMENTATION READINESS, SYNTHETIC ACCEPTANCE AND PRODUCTION LAUNCH REMAIN BLOCKED; PACKAGE GATE IMPACT IS NONE'
] as const;

export type G36GovernanceRow = {
  readonly matrixRow: string;
  readonly frozenBoundary: string;
};

export const G36_GOVERNANCE_MATRIX: readonly G36GovernanceRow[] = [
  { matrixRow: 'MERGED_IDENTITY_TWO_PRIMARY_MEMBERS_PRESERVED_WITHOUT_PARAMETER_FAMILY_COLLAPSE', frozenBoundary: 'MERGED_IDENTITY_TWO_PRIMARY_MEMBERS_PRESERVED_WITHOUT_PARAMETER_FAMILY_COLLAPSE' },
  { matrixRow: 'SOURCE_NORMATIVE_DECISION_OWNER_ARTIFACT_OWNER_APPROVER_AND_EVIDENCE_ROLE_SEPARATION', frozenBoundary: 'SOURCE_NORMATIVE_DECISION_OWNER_ARTIFACT_OWNER_APPROVER_AND_EVIDENCE_ROLE_SEPARATION' },
  { matrixRow: 'GLOBAL_STARTING_SEGMENT_MINIMUM_THRESHOLD_AND_MATCH_COMPONENT_PARAMETER_FAMILIES_REMAIN_DISTINCT', frozenBoundary: 'GLOBAL_STARTING_SEGMENT_MINIMUM_THRESHOLD_AND_MATCH_COMPONENT_PARAMETER_FAMILIES_REMAIN_DISTINCT' },
  { matrixRow: 'SEPARATELY_APPROVED_GLOBAL_BASELINE_IS_SOLE_AUTHORITY_ABSENT_APPROVED_VERSION_HASH_BOUND_LAWFUL_OVERRIDE', frozenBoundary: 'SEPARATELY_APPROVED_GLOBAL_BASELINE_IS_SOLE_AUTHORITY_ABSENT_APPROVED_VERSION_HASH_BOUND_LAWFUL_OVERRIDE' },
  { matrixRow: 'SEGMENT_MEMBERSHIP_MUST_BE_EXPLICIT_SOURCE_AUTHORITATIVE_LAWFUL_APPLICABLE_AND_NEVER_INFERRED_PROXY_OR_DEFAULTED', frozenBoundary: 'SEGMENT_MEMBERSHIP_MUST_BE_EXPLICIT_SOURCE_AUTHORITATIVE_LAWFUL_APPLICABLE_AND_NEVER_INFERRED_PROXY_OR_DEFAULTED' },
  { matrixRow: 'CONFIRMED_HARD_CONSTRAINT_PRE_SCORING_PRECEDENCE_AND_NON_COMPENSATION', frozenBoundary: 'CONFIRMED_HARD_CONSTRAINT_PRE_SCORING_PRECEDENCE_AND_NON_COMPENSATION' },
  { matrixRow: 'AFFECTED_USE_FAIL_CLOSED_WITHOUT_ZERO_EQUAL_NEUTRAL_PREVIOUS_NEAREST_HEURISTIC_AI_DEFAULT_OR_NEGATIVE_FACT', frozenBoundary: 'AFFECTED_USE_FAIL_CLOSED_WITHOUT_ZERO_EQUAL_NEUTRAL_PREVIOUS_NEAREST_HEURISTIC_AI_DEFAULT_OR_NEGATIVE_FACT' },
  { matrixRow: 'IMMUTABLE_VERSION_HASH_BOUND_FROZEN_PREREGISTERED_EVIDENCE_PREREQUISITES_DO_NOT_APPROVE_EXACT_CONTENT', frozenBoundary: 'IMMUTABLE_VERSION_HASH_BOUND_FROZEN_PREREGISTERED_EVIDENCE_PREREQUISITES_DO_NOT_APPROVE_EXACT_CONTENT' },
  { matrixRow: 'HISTORICAL_RESULTS_REMAIN_BOUND_TO_ACTUAL_POLICY_VERSION_HASH_AND_ARE_NEVER_SILENTLY_RECALCULATED_OR_RELABELED', frozenBoundary: 'HISTORICAL_RESULTS_REMAIN_BOUND_TO_ACTUAL_POLICY_VERSION_HASH_AND_ARE_NEVER_SILENTLY_RECALCULATED_OR_RELABELED' },
  { matrixRow: 'INDEPENDENT_SCORING_CONFIDENCE_QUALIFICATION_RISK_RANKING_AND_EVALUATION_BOUNDARIES_SUPPLY_NO_WEIGHT_OR_THRESHOLD', frozenBoundary: 'INDEPENDENT_SCORING_CONFIDENCE_QUALIFICATION_RISK_RANKING_AND_EVALUATION_BOUNDARIES_SUPPLY_NO_WEIGHT_OR_THRESHOLD' },
  { matrixRow: 'SYNTHETIC_EVALUATION_OR_TECHNICAL_SUCCESS_CREATES_NO_PRODUCTION_POLICY_RUNTIME_OR_AUTOMATIC_ACTION', frozenBoundary: 'SYNTHETIC_EVALUATION_OR_TECHNICAL_SUCCESS_CREATES_NO_PRODUCTION_POLICY_RUNTIME_OR_AUTOMATIC_ACTION' },
  { matrixRow: 'PARTIALLY_RESOLVED_BOUNDARY_EXACT_WEIGHT_THRESHOLD_FORMULA_SEGMENT_DATA_POLICY_RUNTIME_CONTENT_OPEN', frozenBoundary: 'PARTIALLY_RESOLVED_BOUNDARY_EXACT_WEIGHT_THRESHOLD_FORMULA_SEGMENT_DATA_POLICY_RUNTIME_CONTENT_OPEN' }
] as const;

export const G36_ROLE_SEPARATION = [
  'XFR-D-M5 SUBSTANTIVE GOVERNANCE OWNER: AI + PRODUCT — SOURCE_NORMATIVE, ARCHITECTURE §37 QUESTION №3',
  'SCORING POLICY ARTIFACT OWNER: Chief AI Architect + PRODUCT — SEPARATELY SOURCE_NORMATIVE, ARCHITECTURE §52',
  'MANDATORY APPROVERS: Chief AI Architect + LEGAL + DEVELOPMENT — HUMAN-APPROVED DECISION-SPECIFIC ASSIGNMENT',
  'EVIDENCE/TECHNICAL-PROCEDURE OWNER: AI + DEVELOPMENT — NO UNILATERAL VALUE, EVIDENCE-SUFFICIENCY, POLICY, PRODUCTION, RELEASE, RUNTIME, IMPLEMENTATION OR GATE AUTHORITY',
  'G36 ASSIGNS NO NEW OWNER, MERGES NO ROLES, WIDENS NO AUTHORITY AND CREATES NO SELF-APPROVAL PATH'
] as const;

export const G36_PARAMETER_AND_AUTHORITY_BOUNDARY = [
  'GLOBAL AND STARTING WEIGHTS, SEGMENT-SPECIFIC WEIGHTS, SEGMENT MINIMUM THRESHOLDS, OTHER MINIMUM THRESHOLDS AND RECIPROCAL FIT ↔ DEAL FEASIBILITY WEIGHTS REMAIN DISTINCT AND SEPARATELY ATTRIBUTABLE',
  'ONE MERGED XFR-D-M5 DECISION PATH DOES NOT COLLAPSE PARAMETER FAMILIES INTO ONE NUMBER, FORMULA, HIERARCHY OR EVIDENCE VERDICT',
  'A SEPARATELY APPROVED GLOBAL BASELINE IS SOLE SCORING AUTHORITY UNLESS A SEPARATELY APPROVED, EVIDENCE-SUPPORTED, VERSION/HASH-BOUND, APPLICABLE LAWFUL SEGMENT OVERRIDE EXISTS',
  'SEGMENT MEMBERSHIP MUST BE EXPLICIT, SOURCE-AUTHORITATIVE, LAWFUL AND APPLICABLE; IT IS NEVER GUESSED, AI-INFERRED, HEURISTIC-DERIVED, PROXY-IMPUTED OR DEFAULTED',
  'MISSING, UNKNOWN, UNCLASSIFIED, AMBIGUOUS, STALE, CONFLICTING, EXPIRED, REVOKED, INCOMPATIBLE, OUT-OF-SCOPE OR UNAUTHORIZED MEMBERSHIP ACTIVATES NO OVERRIDE',
  'A SEPARATELY APPROVED APPLICABLE CONFIRMED HARD CONSTRAINT IS HANDLED BEFORE SCORING AND CANNOT BE SOFTENED OR COMPENSATED BY ANY WEIGHT, THRESHOLD, SCORE, AGGREGATE OR FAVORABLE EVIDENCE'
] as const;

export const G36_FAIL_CLOSED_AND_EVIDENCE = [
  'MISSING OR INCOMPATIBLE POLICY, VALUE, THRESHOLD, SOURCE, EVIDENCE, VERSION/HASH OR COMPATIBILITY BLOCKS ONLY THE AFFECTED SCORING OR APPROVAL PROGRESSION UNLESS ANOTHER APPROVED COMPATIBLE RULE APPLIES',
  'NO ZERO, EQUAL, AVERAGE, NEUTRAL, PREVIOUS, NEAREST, WORST, BEST, HEURISTIC OR AI-INFERRED DEFAULT IS CREATED',
  'FAILURE CREATES NO NEGATIVE FIT FACT, CONFIRMED FAILURE, HARD CONSTRAINT, REJECTION, QUALIFICATION OR RISK RESULT, ROUTE, REASON OR USER-FACING STATEMENT',
  'WEIGHT-POLICY EVIDENCE CANNOT COMPENSATE MISSING OR ADVERSE EVIDENCE IN ANOTHER PARAMETER FAMILY, SEGMENT, INTERSECTION, FAIRNESS SLICE, CONFIDENCE, RISK, QUALIFICATION OR INDEPENDENT SAFEGUARD',
  'IMMUTABLE VERSION/HASH-BOUND FROZEN PREREGISTERED EVIDENCE, BASELINE-FIRST HISTORY, TUNING/FINAL ISOLATION, COMPATIBLE COMPARISON, SEPARATE REPORTING AND NON-COMPENSATION ARE PREREQUISITES, NOT APPROVALS',
  'HISTORICAL RESULTS REMAIN BOUND TO ACTUAL INPUTS AND POLICY VERSION/HASH AND ARE NEVER SILENTLY RECALCULATED, RELABELED OR OVERWRITTEN',
  'SYNTHETIC, EVALUATION OR TECHNICAL SUCCESS CREATES NO PRODUCTION CLAIM AND NO RESULT AUTOMATICALLY CHANGES POLICY, MODEL, WEIGHT, THRESHOLD, RANK, ROUTE, RELEASE, RUNTIME OR GATE'
] as const;

export const G36_OPEN_CONTENT = [
  'GLOBAL, STARTING, PER-FEATURE, PER-DIMENSION, PER-SIDE, PER-SEGMENT AND PER-INTERSECTION WEIGHTS',
  'RECIPROCAL FIT ↔ DEAL FEASIBILITY RATIO, SIGN, SCALE, FORMULA, NORMALIZATION, NUMERATOR, DENOMINATOR AND ARITHMETIC TREATMENT',
  'MINIMUM-THRESHOLD VALUE, TARGET COMPONENT, COMPARATOR, INCLUSIVITY, SCOPE, DENOMINATOR, AGGREGATION, APPLICABILITY AND FALLBACK',
  'SEGMENT UNIVERSE, INTERSECTIONS, MEMBERSHIP SOURCE/RULES, PROTECTED/PROXY CLASSIFICATION AND LAWFUL BASIS',
  'GLOBAL BASELINE, SEGMENT OVERRIDE AND APPLICABILITY CONTENT',
  'MUTUAL AGGREGATE, CRITERION-CLASS WEIGHTING, EVIDENCE CONFIDENCE CALIBRATION, QUALIFICATION AND RANKING CONTENT',
  'NUMERIC REPRESENTATION, PRECISION, ROUNDING, EQUALITY, SERIALIZATION AND REPLAY MECHANICS',
  'DATASET, SAMPLE, SOURCE, ALLOCATION, SPLIT, SEED, LABEL, ADJUDICATION, CORRECTION, METRIC, TARGET, UNCERTAINTY, STATISTIC, RESULT AND VERDICT',
  'ACTUAL EVIDENCE PACKAGE, EVALUATION RUN, PRODUCTION-DATA AUTHORITY, APPLICABILITY AND READINESS',
  'POLICY, MANIFEST, SCHEMA, CARRIER, API, DB, EVENT, REASON CODE, RBAC, RUNTIME, MONITORING, ROLLBACK, MIGRATION, IMPLEMENTATION AND GATES'
] as const;

export const G36_PROHIBITED_SURROGATES = [
  'THE 0.5/0.5 NEUTRAL EVALUATION BASELINE IS NOT AN APPROVED, DEFAULT OR RECOMMENDED WEIGHT POLICY',
  'THE 100-CAMPAIGN PILOT CAP AND CAMPAIGN-TO-QUALIFIED 40% TARGET OR 25% STOP LEVEL SUPPLY NO WEIGHT, THRESHOLD, RATIO, TARGET OR ACCEPTANCE VALUE',
  'XFR-D-017 THROUGH XFR-D-026, XFR-D-M4, XFR-D-M6, QUALIFICATION AND EVALUATION DECISIONS REMAIN INDEPENDENT AND SUPPLY NO XFR-D-M5 VALUE OR AUTOMATIC AUTHORITY'
] as const;

export const G36_NON_DECISION_RESULT =
  'G36 NON-DECISION RESULT: NO WEIGHT, RATIO, SIGN, SCALE, FORMULA, NORMALIZATION, NUMERATOR, DENOMINATOR, THRESHOLD, SEGMENT, MEMBERSHIP, LAWFUL BASIS, OVERRIDE, DATASET, METRIC, STATISTIC, POLICY, MANIFEST, PRODUCTION-DATA USE, SCHEMA, CARRIER, API, DB, EVENT, RUNTIME, MONITORING, ROLLBACK, MIGRATION OR IMPLEMENTATION IS SELECTED, CALCULATED OR APPROVED. XFR-D-M5 v1.0 REMAINS PARTIALLY_RESOLVED_BOUNDARY; MSP-02 AND MSP-03 REMAIN PRIMARY_MERGED_MEMBER OF XFR-D-M5. SYNTHETIC OR TECHNICAL SUCCESS CREATES NO PRODUCTION CLAIM, GATE IMPACT IS NONE, AND ALL THREE GOVERNANCE GATES REMAIN BLOCKED.' as const;

export const G36_TERMINAL_TOKEN =
  'G36_SYNTHETIC_NO_WEIGHT_RATIO_FORMULA_NORMALIZATION_THRESHOLD_SEGMENT_OVERRIDE_POLICY_PRODUCTION_OR_RUNTIME_USE_SELECTED' as const;

export const G36_TERMINAL_LINE =
  'NO WEIGHT, RATIO, FORMULA, NORMALIZATION, THRESHOLD, SEGMENT OVERRIDE, DATA, POLICY, PRODUCTION, RUNTIME OR IMPLEMENTATION ACTION OCCURRED' as const;
