export const G37_TITLE =
  'SYNTHETIC JOINT-CALIBRATION QUALITATIVE GOVERNANCE REFERENCE — NOT PRODUCTION APPROVED' as const;

export const G37_DISCLAIMER =
  'MANUAL DEV-ONLY REFERENCE — QUALITATIVE FEATURE FIT ↔ EVIDENCE CONFIDENCE GOVERNANCE AND EVIDENCE BOUNDARY ONLY' as const;

export const G37_SCOPE_LINE =
  'NO MAPPING, FUNCTION, ORDER, VALUE, RANGE, CALIBRATION, POLICY OR RUNTIME USE SELECTED' as const;

export const G37_REGIONS = [
  'SOURCE AND STATUS BOUNDARY',
  'JOINT-CALIBRATION QUALITATIVE MATRIX',
  'ROLE AND ARTIFACT-OWNER SEPARATION',
  'SEMANTIC, ENUM, FAIL-CLOSED AND NON-COMPENSATION BOUNDARY',
  'OPEN EXACT CONTENT',
  'NON-DECISION RESULT'
] as const;

export const G37_SOURCE_BOUNDARY = [
  'SOURCE DECISION: XFR-D-M6 v1.0 — PARTIALLY_RESOLVED_BOUNDARY',
  'CANONICAL MERGED IDENTITY: FS-12 + MSP-12 → XFR-D-M6 — BOTH SOURCE KEYS REMAIN PRIMARY_MERGED_MEMBER',
  'INVENTORY COUNTS: 102 SOURCE KEYS / 90 CANONICAL IDS — UNCHANGED',
  'APPROVED BOUNDARY IS QUALITATIVE ONLY: SEMANTIC AND ROLE SEPARATION; CATEGORICAL ENUM PRESERVATION; CLOSED FUTURE CANDIDATE; AFFECTED-USE FAIL-CLOSED; DOUBLE-COUNTING REVIEW; NON-COMPENSATION; IMMUTABLE EVIDENCE; HISTORICAL INTEGRITY; AND NO AUTOMATIC ACTION',
  'EVERY EXACT MAPPING, FUNCTION, ORDER, HIERARCHY, VALUE, RANGE, DIRECTION, MONOTONICITY, DEFAULT, FALLBACK, NORMALIZATION, DATASET, METRIC, STATISTIC, POLICY, PRODUCTION-DATA USE, SCHEMA, CARRIER, API, DB, EVENT, RUNTIME AND IMPLEMENTATION CONTENT REMAINS OPEN',
  'IMPLEMENTATION READINESS, SYNTHETIC ACCEPTANCE AND PRODUCTION LAUNCH REMAIN BLOCKED; PACKAGE GATE IMPACT IS NONE'
] as const;

export type G37GovernanceRow = {
  readonly matrixRow: string;
  readonly frozenBoundary: string;
};

export const G37_GOVERNANCE_MATRIX: readonly G37GovernanceRow[] = [
  { matrixRow: 'MERGED_IDENTITY_TWO_PRIMARY_MEMBERS_PRESERVED_WITHOUT_ARTIFACT_OWNER_OR_SEMANTIC_COLLAPSE', frozenBoundary: 'MERGED_IDENTITY_TWO_PRIMARY_MEMBERS_PRESERVED_WITHOUT_ARTIFACT_OWNER_OR_SEMANTIC_COLLAPSE' },
  { matrixRow: 'CANDIDATE_DERIVED_GOVERNANCE_OWNER_THREE_ARTIFACT_OWNERS_APPROVERS_AND_EVIDENCE_ROLE_REMAIN_SEPARATE', frozenBoundary: 'CANDIDATE_DERIVED_GOVERNANCE_OWNER_THREE_ARTIFACT_OWNERS_APPROVERS_AND_EVIDENCE_ROLE_REMAIN_SEPARATE' },
  { matrixRow: 'FEATURE_FIT_FEATURE_WEIGHT_EVIDENCE_STATUS_EVIDENCE_CONFIDENCE_REQUIRED_EVIDENCE_OVERALL_CONFIDENCE_ELIGIBILITY_RISK_AND_QUALIFICATION_REMAIN_DISTINCT', frozenBoundary: 'FEATURE_FIT_FEATURE_WEIGHT_EVIDENCE_STATUS_EVIDENCE_CONFIDENCE_REQUIRED_EVIDENCE_OVERALL_CONFIDENCE_ELIGIBILITY_RISK_AND_QUALIFICATION_REMAIN_DISTINCT' },
  { matrixRow: 'EXACT_SEVEN_VALUE_EVIDENCE_STATUS_ENUM_REMAINS_CATEGORICAL_WITHOUT_NUMERIC_ORDER_HIERARCHY_RANK_DIRECTION_OR_DEFAULT', frozenBoundary: 'EXACT_SEVEN_VALUE_EVIDENCE_STATUS_ENUM_REMAINS_CATEGORICAL_WITHOUT_NUMERIC_ORDER_HIERARCHY_RANK_DIRECTION_OR_DEFAULT' },
  { matrixRow: 'FUTURE_JOINT_CALIBRATION_CANDIDATE_MUST_BE_CLOSED_EXPLICIT_IMMUTABLE_VERSIONED_HASH_BOUND_AUDITABLE_AND_REPRODUCIBLE', frozenBoundary: 'FUTURE_JOINT_CALIBRATION_CANDIDATE_MUST_BE_CLOSED_EXPLICIT_IMMUTABLE_VERSIONED_HASH_BOUND_AUDITABLE_AND_REPRODUCIBLE' },
  { matrixRow: 'AFFECTED_USE_FAIL_CLOSED_WITHOUT_NUMERIC_DEFAULT_NEGATIVE_FIT_EVIDENCE_PROMOTION_BUSINESS_VERDICT_ROUTE_REASON_OR_PRESENTATION_AUTHORITY', frozenBoundary: 'AFFECTED_USE_FAIL_CLOSED_WITHOUT_NUMERIC_DEFAULT_NEGATIVE_FIT_EVIDENCE_PROMOTION_BUSINESS_VERDICT_ROUTE_REASON_OR_PRESENTATION_AUTHORITY' },
  { matrixRow: 'DOUBLE_COUNTING_ANALYSIS_NON_COMPENSATION_AND_SEPARATE_ADVERSE_NULL_INCOMPATIBLE_UNEVALUABLE_REPORTING_REQUIRED', frozenBoundary: 'DOUBLE_COUNTING_ANALYSIS_NON_COMPENSATION_AND_SEPARATE_ADVERSE_NULL_INCOMPATIBLE_UNEVALUABLE_REPORTING_REQUIRED' },
  { matrixRow: 'IMMUTABLE_FROZEN_PREREGISTERED_EVIDENCE_PREREQUISITES_DO_NOT_APPROVE_EXACT_CALIBRATION_CONTENT', frozenBoundary: 'IMMUTABLE_FROZEN_PREREGISTERED_EVIDENCE_PREREQUISITES_DO_NOT_APPROVE_EXACT_CALIBRATION_CONTENT' },
  { matrixRow: 'HISTORICAL_RESULTS_REMAIN_BOUND_TO_ACTUAL_SCHEMA_POLICY_EVIDENCE_AND_IMPLEMENTATION_VERSION_HASH', frozenBoundary: 'HISTORICAL_RESULTS_REMAIN_BOUND_TO_ACTUAL_SCHEMA_POLICY_EVIDENCE_AND_IMPLEMENTATION_VERSION_HASH' },
  { matrixRow: 'INDEPENDENT_SCORING_EVALUATION_RISK_QUALIFICATION_AND_SIBLING_DECISIONS_SUPPLY_NO_MAPPING_FUNCTION_VALUE_OR_RANGE', frozenBoundary: 'INDEPENDENT_SCORING_EVALUATION_RISK_QUALIFICATION_AND_SIBLING_DECISIONS_SUPPLY_NO_MAPPING_FUNCTION_VALUE_OR_RANGE' },
  { matrixRow: 'SYNTHETIC_REPLAY_EVALUATION_OR_TECHNICAL_SUCCESS_CREATES_NO_PRODUCTION_POLICY_RUNTIME_OR_AUTOMATIC_ACTION', frozenBoundary: 'SYNTHETIC_REPLAY_EVALUATION_OR_TECHNICAL_SUCCESS_CREATES_NO_PRODUCTION_POLICY_RUNTIME_OR_AUTOMATIC_ACTION' },
  { matrixRow: 'PARTIALLY_RESOLVED_BOUNDARY_EXACT_MAPPING_FUNCTION_ORDER_VALUE_RANGE_DATA_POLICY_RUNTIME_CONTENT_OPEN', frozenBoundary: 'PARTIALLY_RESOLVED_BOUNDARY_EXACT_MAPPING_FUNCTION_ORDER_VALUE_RANGE_DATA_POLICY_RUNTIME_CONTENT_OPEN' }
] as const;

export const G37_ROLE_SEPARATION = [
  'XFR-D-M6 SUBSTANTIVE GOVERNANCE OWNER: Chief AI Architect + AI — HUMAN-APPROVED CANDIDATE-DERIVED ASSIGNMENT, NOT SOURCE_NORMATIVE',
  'SCORING POLICY ARTIFACT OWNER: Chief AI Architect + PRODUCT',
  'FEATURE SCHEMA ARTIFACT OWNER: PRODUCT + LEGAL + AI',
  'EVALUATION PLAN/EVIDENCE ARTIFACT OWNER: AI + DEVELOPMENT',
  'MANDATORY APPROVERS: PRODUCT + LEGAL + DEVELOPMENT',
  'EVIDENCE/TECHNICAL-PROCEDURE OWNER: AI + DEVELOPMENT — NO UNILATERAL MAPPING, VALUE, EVIDENCE-SUFFICIENCY, POLICY, PRODUCTION, RELEASE, RUNTIME, IMPLEMENTATION OR GATE AUTHORITY',
  'G37 ASSIGNS NO NEW OWNER, MERGES NO ROLES, WIDENS NO AUTHORITY AND CREATES NO SELF-APPROVAL PATH'
] as const;

export const G37_EXACT_EVIDENCE_STATUS_ENUM = [
  'UNVERIFIED',
  'SOURCE_CONFIRMED',
  'CONTENT_VERIFIED',
  'CONFLICTING',
  'STALE',
  'REJECTED',
  'HUMAN_REVIEW_REQUIRED'
] as const;

export const G37_SEMANTIC_AND_FAIL_CLOSED_BOUNDARY = [
  'FEATURE FIT, FEATURE WEIGHT, EVIDENCE STATUS, FEATURE/VALUE EVIDENCE CONFIDENCE, REQUIRED EVIDENCE LEVEL, OVERALL CONFIDENCE, HARD CONSTRAINT/ELIGIBILITY, RISK AND QUALIFICATION REMAIN DISTINCT AND SEPARATELY ATTRIBUTABLE',
  'THE SEVEN-VALUE EVIDENCE STATUS ENUM IS CATEGORICAL AND HAS NO APPROVED NUMERIC ORDER, HIERARCHY, RANK, DIRECTION, VALUE, RANGE OR DEFAULT',
  'ANY FUTURE JOINT-CALIBRATION CANDIDATE MUST BE CLOSED, EXPLICIT, IMMUTABLE, VERSION/HASH-BOUND, AUDITABLE AND REPRODUCIBLE',
  'MISSING, UNKNOWN, STALE, CONFLICTING, REJECTED, HUMAN-REVIEW-REQUIRED, INCOMPATIBLE, OUT-OF-SCOPE, UNAUTHORIZED OR VERSION/HASH-MISMATCHED MATERIAL BLOCKS ONLY THE AFFECTED GOVERNED USE',
  'NO ZERO, ONE, MIDPOINT, EQUAL, AVERAGE, NEAREST, NEUTRAL, MINIMUM, MAXIMUM, PREVIOUS, HEURISTIC OR AI-DERIVED DEFAULT; EVIDENCE PROMOTION; NEGATIVE-FIT COERCION; OR BUSINESS VERDICT IS CREATED',
  'DOUBLE-COUNTING ANALYSIS AND NON-COMPENSATION ARE MANDATORY; FAVORABLE AGGREGATE EVIDENCE CANNOT ERASE AN ADVERSE, NULL, INCOMPATIBLE OR UNEVALUABLE INDEPENDENT DIMENSION',
  'IMMUTABLE VERSION/HASH-BOUND FROZEN PREREGISTERED EVIDENCE, TUNING/FINAL SEPARATION, COMPATIBLE COMPARISON, UNCERTAINTY, COUNTER-EVIDENCE AND SEPARATE REPORTING ARE PREREQUISITES, NOT APPROVALS',
  'HISTORICAL RESULTS REMAIN BOUND TO ACTUAL FEATURE SCHEMA, SCORING POLICY, EVIDENCE AND IMPLEMENTATION VERSIONS/HASHES AND ARE NEVER SILENTLY RECALCULATED, RELABELED OR OVERWRITTEN',
  'SYNTHETIC REPLAY, EVALUATION OR TECHNICAL SUCCESS CREATES NO PRODUCTION CLAIM AND NO RESULT AUTOMATICALLY CHANGES MODEL, POLICY, RUNTIME, RELEASE OR GATE'
] as const;

export const G37_OPEN_CONTENT = [
  'FEATURE FIT AND EVIDENCE CONFIDENCE MAPPING TABLE, MAPPING FUNCTION AND JOINT FUNCTIONAL FORM',
  'NUMERIC ORDER, HIERARCHY, VALUE, RANGE, DIRECTION, MONOTONICITY, DEFAULT AND FALLBACK',
  'FEATURE, SOURCE, STATUS, PURPOSE, USE-SPECIFIC CALIBRATION APPLICABILITY AND EXCEPTIONS',
  'PROPOSAL [0,1] OR ANY RANGE AS AN APPROVED INTERFACE OR RUNTIME CONTRACT',
  'MULTIPLICATION, NORMALIZATION, NUMERATOR, DENOMINATOR, MISSING ARITHMETIC, ZERO-ACTIVE-WEIGHT AND DOUBLE-COUNTING TREATMENT',
  'FEATURE WEIGHT, CRITERION CLASS, GLOBAL OR SEGMENT WEIGHT POLICY, REQUIRED EVIDENCE AND SUFFICIENCY RULES',
  'DATASET, SOURCE, SAMPLE, ALLOCATION, SPLIT, SEED, LABEL, ADJUDICATION, CORRECTION AND FROZEN MANIFEST',
  'METRIC, TARGET, OBJECTIVE, LOSS, UNCERTAINTY, AGGREGATION, TOLERANCE, INTERVAL, WINDOW, TEST, STATISTIC, RESULT AND VERDICT',
  'PRECISION, ROUNDING, SERIALIZATION, REPLAY, PRODUCTION-DATA AUTHORITY, LAWFUL APPLICABILITY, CALIBRATION AND READINESS',
  'POLICY, MANIFEST, SCHEMA, CARRIER, API, DB, EVENT, STORAGE, REASON CODE, RBAC, RUNTIME, MONITORING, ROLLBACK, MIGRATION, IMPLEMENTATION AND GATES'
] as const;

export const G37_INDEPENDENT_BOUNDARIES = [
  'THE PROPOSAL/CANDIDATE [0,1] NOTATION IS NOT AN APPROVED RANGE, INTERFACE OR RUNTIME CONTRACT',
  'INDEPENDENT SCORING, EVALUATION, RISK, QUALIFICATION AND SIBLING DECISIONS SUPPLY NO XFR-D-M6 MAPPING, FUNCTION, VALUE OR RANGE',
  'NO CONFIDENCE, SCORE, RISK, QUALIFICATION, ELIGIBILITY, RANK, ROUTE, REASON CODE OR PRESENTATION AUTHORITY IS DERIVED BY THIS REFERENCE'
] as const;

export const G37_NON_DECISION_RESULT =
  'G37 NON-DECISION RESULT: NO MAPPING, FUNCTION, ORDER, HIERARCHY, VALUE, RANGE, DIRECTION, MONOTONICITY, DEFAULT, FALLBACK, CALIBRATION, FORMULA, NORMALIZATION, NUMERATOR, DENOMINATOR, DATASET, METRIC, STATISTIC, POLICY, MANIFEST, PRODUCTION-DATA USE, SCHEMA, CARRIER, API, DB, EVENT, RUNTIME, MONITORING, ROLLBACK, MIGRATION OR IMPLEMENTATION IS SELECTED, CALCULATED OR APPROVED. XFR-D-M6 v1.0 REMAINS PARTIALLY_RESOLVED_BOUNDARY; FS-12 AND MSP-12 REMAIN PRIMARY_MERGED_MEMBER OF XFR-D-M6. SYNTHETIC OR TECHNICAL SUCCESS CREATES NO PRODUCTION CLAIM, GATE IMPACT IS NONE, AND ALL THREE GOVERNANCE GATES REMAIN BLOCKED.' as const;

export const G37_TERMINAL_TOKEN =
  'G37_SYNTHETIC_NO_MAPPING_FUNCTION_ORDER_VALUE_RANGE_CALIBRATION_POLICY_PRODUCTION_OR_RUNTIME_USE_SELECTED' as const;

export const G37_TERMINAL_LINE =
  'NO MAPPING, FUNCTION, ORDER, VALUE, RANGE, CALIBRATION, DATA, POLICY, PRODUCTION, RUNTIME OR IMPLEMENTATION ACTION OCCURRED' as const;
