export const SYNTHETIC_HARD_CONSTRAINT_LEGAL_VERDICT_TITLE =
  'SYNTHETIC HARD-CONSTRAINT LEGAL-VERDICT BOUNDARY REFERENCE — NOT PRODUCTION APPROVED' as const;

export const SYNTHETIC_HARD_CONSTRAINT_LEGAL_VERDICT_DISCLAIMER =
  'MANUAL DEV-ONLY REFERENCE — PRE-AUTHORED SOURCE COPY ONLY' as const;

export const SYNTHETIC_HARD_CONSTRAINT_LEGAL_VERDICT_SCOPE_LINE =
  'NO LEGAL VERDICT OR ELIGIBILITY ACTION EXECUTED' as const;

export const SYNTHETIC_HARD_CONSTRAINT_LEGAL_VERDICT_REGIONS_IN_ORDER = [
  'SOURCE AND STATUS BOUNDARY',
  'TWENTY CANDIDATES — NO FINAL LEGAL VERDICT',
  'CONFIRMED PROTECTED/PROXY — UNCONDITIONAL CANDIDATE EXCLUSION',
  'MISSING OR CONFLICTING EVIDENCE — PROMOTION BLOCKED ONLY',
  'NON-DECISION RESULT'
] as const;

export const SYNTHETIC_HARD_CONSTRAINT_LEGAL_VERDICT_SOURCE_BOUNDARY = [
  'SOURCE: XFR-D-014 v1.0 — PARTIALLY_RESOLVED_BOUNDARY',
  'CANONICAL IDENTITY: FS-17 → XFR-D-014 — PRIMARY_STANDALONE',
  'ALL 20 FEATURE SCHEMA §5.1 ROWS REMAIN ELIGIBILITY_HARD_CONSTRAINT_CANDIDATE',
  'NO CANDIDATE HAS A FINAL LEGAL VERDICT',
  'automatic_ineligible_allowed = NO — ALL THREE GOVERNANCE GATES REMAIN BLOCKED'
] as const;

export const SYNTHETIC_HARD_CONSTRAINT_LEGAL_VERDICT_CANDIDATES = [
  { ordinal: 1, featureId: 'property_type_membership' },
  { ordinal: 2, featureId: 'area_range_fit' },
  { ordinal: 3, featureId: 'budget_fit' },
  { ordinal: 4, featureId: 'rent_rate_fit' },
  { ordinal: 5, featureId: 'business_category_allowed' },
  { ordinal: 6, featureId: 'condition_acceptability' },
  { ordinal: 7, featureId: 'timing_compatibility' },
  { ordinal: 8, featureId: 'entrance_requirement_fit' },
  { ordinal: 9, featureId: 'required_features_present' },
  { ordinal: 10, featureId: 'excluded_features_absent' },
  { ordinal: 11, featureId: 'loading_access_required_fit' },
  { ordinal: 12, featureId: 'power_min_fit' },
  { ordinal: 13, featureId: 'ceiling_height_min_fit' },
  { ordinal: 14, featureId: 'parking_min_fit' },
  { ordinal: 15, featureId: 'access_mode_hard_fit' },
  { ordinal: 16, featureId: 'country_code_membership' },
  { ordinal: 17, featureId: 'region_membership' },
  { ordinal: 18, featureId: 'city_membership' },
  { ordinal: 19, featureId: 'districts_membership' },
  { ordinal: 20, featureId: 'floor_option_fit' }
] as const;

export const SYNTHETIC_HARD_CONSTRAINT_LEGAL_VERDICT_CANDIDATE_STATUS =
  'ELIGIBILITY_HARD_CONSTRAINT_CANDIDATE' as const;

export const SYNTHETIC_HARD_CONSTRAINT_LEGAL_VERDICT_AUTOMATIC_INELIGIBLE = 'NO' as const;

export const SYNTHETIC_HARD_CONSTRAINT_LEGAL_VERDICT_CONFIRMED_RESTRICTION_BOUNDARY = [
  'A FUTURE CONFIRMED PROTECTED, PROXY OR DISCRIMINATORILY RESTRICTED CANDIDATE/USE IS UNCONDITIONALLY EXCLUDED FROM HARD CONSTRAINT ELIGIBILITY',
  'THE EXCLUSION APPLIES TO THE CANDIDATE/USE ONLY — IT NEVER REJECTS OR MARKS A USER INELIGIBLE',
  'LAWFUL BASIS CANNOT OVERRIDE A PROHIBITION',
  'EACH FUTURE ITEM-SPECIFIC VERDICT REQUIRES A SEPARATE VERSION/HASH-BOUND EVIDENCE-BACKED DECISION'
] as const;

export const SYNTHETIC_HARD_CONSTRAINT_LEGAL_VERDICT_EVIDENCE_BOUNDARY = [
  'MISSING, UNKNOWN, UNCLASSIFIED, STALE OR CONFLICTING EVIDENCE BLOCKS PROMOTION OF THE AFFECTED CANDIDATE ONLY',
  'MISSING OR CONFLICTING EVIDENCE CREATES NO NEGATIVE FACT, FAILURE, REJECTION, EXCLUSION OR AUTOMATIC INELIGIBLE',
  'EXACT VERDICTS, CLASSIFICATIONS, LAWFUL BASIS, COMPATIBILITY AND EVIDENCE SUFFICIENCY REMAIN OPEN',
  'DATASET, POLICY, DATA CONTRACT, CARRIER, MANIFEST, RUNTIME, IMPLEMENTATION AND OPERATIONAL CONSEQUENCES REMAIN OPEN',
  'NO SCORE, CONFIDENCE, QUALIFICATION, RISK, RANKING, RECOMMENDATION OR ROUTING IS AUTHORIZED'
] as const;

export const SYNTHETIC_HARD_CONSTRAINT_LEGAL_VERDICT_TERMINAL_TOKEN =
  'SYNTHETIC_NO_LEGAL_VERDICT_OR_ELIGIBILITY_ACTION_EXECUTED' as const;

export const SYNTHETIC_HARD_CONSTRAINT_LEGAL_VERDICT_TERMINAL_LINE =
  'NO LEGAL VERDICT OR ELIGIBILITY ACTION EXECUTED — NO CANDIDATE APPROVAL, CLASSIFICATION, PROMOTION, REJECTION, INELIGIBLE, SCORE, QUALIFICATION, RISK, RANKING, RECOMMENDATION OR ROUTING OCCURRED' as const;

