export const SYNTHETIC_MATCH_REVIEW_WORKSPACE_TITLE =
  'SYNTHETIC MATCH REVIEW WORKSPACE — NOT PRODUCTION APPROVED' as const;

export const SYNTHETIC_MATCH_REVIEW_WORKSPACE_DISCLAIMER =
  'MANUAL DEV-ONLY REHEARSAL — NO DEAL EXECUTION' as const;

export const SYNTHETIC_MATCH_REVIEW_WORKSPACE_CO_DISPLAY_WARNING =
  'CO-DISPLAY ONLY — NOT COMPARED OR MATCHED' as const;

export const SYNTHETIC_MATCH_REVIEW_WORKSPACE_PAIR_WARNING =
  'FIXTURE ONLY — NOT MATCHED OR RANKED' as const;

export const SYNTHETIC_MATCH_REVIEW_WORKSPACE_FIXTURE_LABEL =
  'PRE-AUTHORED SYNTHETIC FIXTURE — NOT COMPUTED' as const;

export const SYNTHETIC_MATCH_REVIEW_WORKSPACE_SELECTION_DISCLAIMER =
  'UI REHEARSAL SELECTION ONLY — NOT APPROVAL' as const;

export const SYNTHETIC_MATCH_REVIEW_WORKSPACE_NON_OCCURRENCE =
  'NO MATCH, SCORE, CONFIDENCE, QUALIFICATION, RISK, RANKING, CONTACT, DEAL OR OUTCOME OCCURRED' as const;

export const SYNTHETIC_MATCH_REVIEW_WORKSPACE_NON_OCCURRENCE_TOKEN =
  'SYNTHETIC_NO_DEAL_EXECUTED' as const;

export const SYNTHETIC_MATCH_REVIEW_WORKSPACE_DISPOSITION_REQUIRED =
  'HUMAN REHEARSAL DISPOSITION REQUIRED' as const;

export const SYNTHETIC_MATCH_REVIEW_WORKSPACE_CONTROLS_ARIA_LABEL =
  'SYNTHETIC MATCH REVIEW WORKSPACE CONTROLS' as const;

export const SYNTHETIC_MATCH_REVIEW_WORKSPACE_DISPOSITION_GROUP_ARIA_LABEL =
  'HUMAN REHEARSAL DISPOSITION' as const;

export const SYNTHETIC_MATCH_REVIEW_WORKSPACE_RESET = 'RESET' as const;

export const SYNTHETIC_MATCH_REVIEW_WORKSPACE_REHEARSAL_CHOICES = [
  'REHEARSE INTEREST',
  'REHEARSE HOLD'
] as const;

export const SYNTHETIC_MATCH_REVIEW_WORKSPACE_OWNER_SIDE = {
  accessibleName: 'OWNER-SIDE NEED',
  line: 'OWNER-SIDE NEED — SYNTHETIC_FIXTURE_PARTY_A'
} as const;

export const SYNTHETIC_MATCH_REVIEW_WORKSPACE_TENANT_SIDE = {
  accessibleName: 'TENANT-SIDE CANDIDATE',
  line: 'TENANT-SIDE CANDIDATE — SYNTHETIC_FIXTURE_PARTY_B'
} as const;

export const SYNTHETIC_MATCH_REVIEW_WORKSPACE_FIXTURE_ROWS = [
  'TEST DEAL TOKEN — SYNTHETIC_TEST_DEAL_A',
  'CAMPAIGN PREVIEW — SYNTHETIC_CAMPAIGN_PREVIEW_A',
  'SAFE PRESENTATION — SYNTHETIC_SAFE_PRESENTATION_A'
] as const;

export const SYNTHETIC_MATCH_REVIEW_WORKSPACE_FLOW_TOKENS_IN_ORDER = [
  'SYNTHETIC_TEST_DEAL_A',
  'SYNTHETIC_CAMPAIGN_PREVIEW_A',
  'SYNTHETIC_FIXTURE_PARTY_A',
  'SYNTHETIC_FIXTURE_PARTY_B',
  'SYNTHETIC_SAFE_PRESENTATION_A',
  'SYNTHETIC_HEADING',
  'SYNTHETIC_MESSAGE',
  'SYNTHETIC_NO_DEAL_EXECUTED'
] as const;

export type SyntheticMatchReviewWorkspaceRehearsalChoice =
  (typeof SYNTHETIC_MATCH_REVIEW_WORKSPACE_REHEARSAL_CHOICES)[number];
