export const SYNTHETIC_MUTUAL_AGGREGATE_TITLE =
  'SYNTHETIC MUTUAL AGGREGATE QUALITATIVE BOUNDARY REFERENCE — NOT PRODUCTION APPROVED' as const;

export const SYNTHETIC_MUTUAL_AGGREGATE_DISCLAIMER =
  'MANUAL DEV-ONLY REFERENCE — QUALITATIVE TWO-INPUT, ANTI-MASKING AND EVIDENCE BOUNDARY ONLY' as const;

export const SYNTHETIC_MUTUAL_AGGREGATE_SCOPE_LINE =
  'NO FUNCTION SELECTION, FORMULA, SCORE OR RUNTIME ACTION EXECUTED' as const;

export const SYNTHETIC_MUTUAL_AGGREGATE_REGIONS_IN_ORDER = [
  'SOURCE AND STATUS BOUNDARY',
  'TWO-INPUT AND ANTI-MASKING MATRIX',
  'CANDIDATES — NAMED BUT NOT SELECTED',
  'EVIDENCE PREREQUISITES AND NON-COMPENSATION',
  'OPEN EXACT CONTENT',
  'NON-DECISION RESULT'
] as const;

export const SYNTHETIC_MUTUAL_AGGREGATE_SOURCE_BOUNDARY = [
  'SOURCE: XFR-D-017 v1.0 — APPROVED PARTIALLY_RESOLVED_BOUNDARY',
  'CANONICAL IDENTITY: MSP-01 → XFR-D-017 — PRIMARY_STANDALONE',
  'SOURCE STRUCTURE ONLY: Reciprocal Fit = Mutual Aggregate(Tenant Fit, Owner Fit)',
  'TENANT FIT AND OWNER FIT REMAIN SEPARATE ATTRIBUTABLE INPUTS',
  'FUNCTION SELECTION AND ALL EXACT CONTENT REMAIN OPEN',
  'ALL THREE GOVERNANCE GATES REMAIN BLOCKED'
] as const;

export type SyntheticMutualAggregateMatrixRow = {
  readonly boundary: string;
  readonly frozenQualitativeMeaning: string;
  readonly explicitProhibition: string;
};

export const SYNTHETIC_MUTUAL_AGGREGATE_MATRIX: readonly SyntheticMutualAggregateMatrixRow[] = [
  {
    boundary: 'TENANT_FIT',
    frozenQualitativeMeaning: 'Separate attributable input',
    explicitProhibition: 'Never derived from, replaced by, dropped in favor of or defaulted from Owner Fit'
  },
  {
    boundary: 'OWNER_FIT',
    frozenQualitativeMeaning: 'Separate attributable input',
    explicitProhibition: 'Never derived from, replaced by, dropped in favor of or defaulted from Tenant Fit'
  },
  {
    boundary: 'TWO_INPUT_STRUCTURE',
    frozenQualitativeMeaning: 'Source structure only',
    explicitProhibition: 'No function, formula, value or computation'
  },
  {
    boundary: 'ANTI_MASKING',
    frozenQualitativeMeaning: 'High Tenant Fit cannot mask critically low Owner Fit, and high Owner Fit cannot mask critically low Tenant Fit',
    explicitProhibition: 'Critically low remains qualitative; no threshold, tolerance or number'
  },
  {
    boundary: 'HARD_CONSTRAINT_PRECEDENCE',
    frozenQualitativeMeaning: 'Independently applicable approved Hard Constraint and Eligibility rules retain pre-scoring precedence',
    explicitProhibition: 'Mutual Aggregate cannot restore or compensate an independently excluded candidate'
  },
  {
    boundary: 'EVIDENCE_NON_COMPENSATION',
    frozenQualitativeMeaning: 'Evidence families and applicable segments remain separately reportable',
    explicitProhibition: 'Favorable aggregate, business or majority-segment evidence cannot hide one-sided-fit failure, an applicable Hard Constraint or Eligibility failure, or missing, adverse, incompatible, unevaluable or insufficient evidence'
  },
  {
    boundary: 'DECISION_MEANING',
    frozenQualitativeMeaning: 'Qualitative boundary only',
    explicitProhibition: 'Not a function, formula, score, Confidence, Risk, Qualification, Priority Score, ranking, recommendation, routing, policy or gate verdict'
  }
] as const;

export const SYNTHETIC_MUTUAL_AGGREGATE_CANDIDATES = [
  { name: 'HARMONIC', status: 'DECISION_CANDIDATE_FOR_REVIEW' },
  { name: 'GEOMETRIC', status: 'DECISION_CANDIDATE_FOR_REVIEW' }
] as const;

export const SYNTHETIC_MUTUAL_AGGREGATE_CANDIDATE_BOUNDARY = [
  'NEITHER CANDIDATE IS SELECTED, RECOMMENDED, ORDERED, PREFERRED, DEFAULTED, USED AS FALLBACK OR REJECTED',
  'NO FORMULA, MATHEMATICAL OPERATOR, NUMERIC EXAMPLE, WEIGHT, THRESHOLD, COMPARISON, COMPUTED OUTPUT OR WINNER',
  'THE NAMED PAIR IS NOT DECLARED PERMANENTLY EXHAUSTIVE FOR EVERY FUTURE POLICY VERSION',
  'NO HIDDEN CANDIDATE, LIBRARY DEFAULT, PREVIOUS-VERSION FALLBACK OR IMPLEMENTATION CONVENIENCE BECOMES A DECISION'
] as const;

export const SYNTHETIC_MUTUAL_AGGREGATE_EVIDENCE_PREREQUISITES = [
  'EXACT IDENTIFIED CANDIDATE POLICY VERSION, HASH AND CONFIGURATION — FOR REVIEW ONLY',
  'ELIGIBLE EVALUATION OBJECT, INPUT PROVENANCE AND LABEL ELIGIBILITY/ADJUDICATION',
  'GROUPING, ENTITY ISOLATION AND CORRECTION HISTORY',
  'FALSE-EXCLUSION, FALSE-ELIGIBILITY AND COUNTER-EVIDENCE WITHOUT CROSS-FAMILY SUBSTITUTION',
  'FROZEN DATASET ALLOCATION, SPLIT, MANIFEST, SEED, LINEAGE AND TUNING/FINAL ISOLATION',
  'SAME-POPULATION, INPUT, POLICY AND LINEAGE COMPATIBLE COMPARISON',
  'PREREGISTERED METRIC, COUNTING, AGGREGATION, UNCERTAINTY AND STATISTICAL PROCEDURE',
  'SEPARATE FAVORABLE, ADVERSE, NULL, INCOMPATIBLE, UNEVALUABLE AND INSUFFICIENT REPORTING',
  'SEGMENT, INTERSECTION, PROTECTED/PROXY AND FAIRNESS REVIEW',
  'DRIFT, POST-FREEZE CORRECTION AND DETERMINISTIC REPLAY',
  'SYNTHETIC-ONLY VERSUS PRODUCTION-DATA APPLICABILITY STATEMENT',
  'LIMITATIONS, UNRESOLVED DEPENDENCIES AND FULL OWNER/APPROVER VERIFICATION'
] as const;

export const SYNTHETIC_MUTUAL_AGGREGATE_EVIDENCE_BOUNDARY = [
  'PREREQUISITES ONLY — NO EXACT CONTENT, SAMPLE, PROCEDURE, METRIC, TEST, RESULT, WINNER OR POLICY APPROVED',
  'NO EVIDENCE FAMILY, FAVORABLE AGGREGATE RESULT OR BUSINESS OUTCOME COMPENSATES FOR MISSING, ADVERSE, INCOMPATIBLE, UNEVALUABLE OR INSUFFICIENT EVIDENCE',
  'UNUSABLE CANDIDATE, EVIDENCE OR BINDING FAILS CLOSED ONLY FOR THE AFFECTED FUNCTION-APPROVAL PROGRESSION',
  'NO NUMERIC ZERO, NEGATIVE FACT, PASS, FAIL, WINNER, INELIGIBLE, REJECTION, QUALIFICATION, RISK, ROUTE, REASON, DISPLAY OR FALLBACK'
] as const;

export const SYNTHETIC_MUTUAL_AGGREGATE_OPEN_CONTENT = [
  'HARMONIC VERSUS GEOMETRIC SELECTION AND FUTURE CANDIDATE-SET EXHAUSTIVENESS',
  'EXACT FORMULA REPRESENTATION AND ZERO, NEAR-ZERO, MISSING-INPUT, OVERFLOW, UNDERFLOW AND OTHER EDGE BEHAVIOR',
  'SCALE, PRECISION, NUMERIC REPRESENTATION, INTERMEDIATE OPERATIONS, ROUNDING AND SERIALIZATION',
  'WEIGHTS, THRESHOLDS, TOLERANCES, CANDIDATE SEARCH AND SELECTION CRITERIA',
  'METRICS, TARGETS, NUMERATOR, DENOMINATOR, COUNTING UNIT, AGGREGATION, WEIGHTING AND UNCERTAINTY',
  'HYPOTHESES, TESTS, ESTIMATORS, INTERVALS, SIGNIFICANCE, MULTIPLICITY AND DECISION RULES',
  'DATASET, SAMPLE, MANIFEST, SPLIT, SEED, LINEAGE, LABELS, ADJUDICATION, SEGMENTS AND INTERSECTIONS',
  'EVIDENCE SUFFICIENCY, COMPARISON RESULT, WINNER, VERDICT AND PRODUCTION APPLICABILITY',
  'POLICY, MANIFEST, VERSION, RELEASE, MONITORING, ROLLBACK AND HISTORICAL BINDING CONTENT',
  'API, EVENT, SCHEMA, DATABASE, STORAGE, TRANSPORT AND RUNTIME CARRIER',
  'ERROR, REASON, RETRY, RECOVERY, ESCALATION, OBSERVABILITY AND OPERATIONAL CONSEQUENCES',
  'SCORING POLICY, DATA CONTRACT, PRODUCTION, RUNTIME, IMPLEMENTATION AND GATES'
] as const;

export const SYNTHETIC_MUTUAL_AGGREGATE_TERMINAL_TOKEN =
  'G26_SYNTHETIC_NO_MUTUAL_AGGREGATE_FUNCTION_OR_SCORE_ACTION_EXECUTED' as const;

export const SYNTHETIC_MUTUAL_AGGREGATE_TERMINAL_LINE =
  'NO FUNCTION SELECTION, FORMULA, WEIGHT, THRESHOLD, COMPUTATION, SCORE, PASS, FAIL, INELIGIBLE, QUALIFICATION, RISK, RANKING, RECOMMENDATION OR ROUTING OCCURRED' as const;
