export const SYNTHETIC_FEATURE_STATE_AXIS_TITLE =
  'SYNTHETIC FEATURE STATE-AXIS SEPARATION REFERENCE — NOT PRODUCTION APPROVED' as const;

export const SYNTHETIC_FEATURE_STATE_AXIS_DISCLAIMER =
  'MANUAL DEV-ONLY REFERENCE — DESIGN-TIME AND CANDIDATE AXES ONLY' as const;

export const SYNTHETIC_FEATURE_STATE_AXIS_SCOPE_LINE =
  'NO RUNTIME ENUM, STATE TRANSITION OR ELIGIBILITY ACTION EXECUTED' as const;

export const SYNTHETIC_FEATURE_STATE_AXIS_REGIONS_IN_ORDER = [
  'SOURCE AND STATUS BOUNDARY',
  'FIVE DISTINCT STATUS DOMAINS',
  'EXACT SOURCE ENUMS — PRESERVED WITHOUT MAPPING',
  'NO COERCION OR SILENT CASCADE',
  'OPEN CONTRACT CONTENT',
  'NON-DECISION RESULT'
] as const;

export const SYNTHETIC_FEATURE_STATE_AXIS_SOURCE_BOUNDARY = [
  'SOURCE: XFR-D-015 v1.0 — APPROVED PARTIALLY_RESOLVED_BOUNDARY',
  'CANONICAL IDENTITY: FS-18 → XFR-D-015 — PRIMARY_STANDALONE',
  'QUALITATIVE AXIS MODEL: READY_FOR_DRAFT — DESIGN-TIME ONLY',
  'EXACT FEATURE SCHEMA ROW 18 CONTENT: BLOCKED_PENDING_DECISION — DESIGN-TIME ONLY',
  'THE TWO STATEMENTS COEXIST WITHOUT RUNTIME READINESS OR CONTRACT APPROVAL',
  'readiness_reason IS SUPPORTING DESIGN-TIME TEXT, NOT A FIFTH registry_readiness VALUE',
  'ALL THREE GOVERNANCE GATES REMAIN BLOCKED'
] as const;

export type SyntheticFeatureStateAxisDomain = {
  readonly statusDomain: string;
  readonly authority: string;
  readonly values: readonly string[];
  readonly status: string;
};

export const SYNTHETIC_FEATURE_STATE_AXIS_DOMAINS: readonly SyntheticFeatureStateAxisDomain[] = [
  {
    statusDomain: 'registry_readiness',
    authority: 'FEATURE_SCHEMA_DESIGN_TIME_ONLY',
    values: ['READY_FOR_DRAFT', 'READY_AS_CANDIDATE_ONLY', 'BLOCKED_PENDING_DECISION', 'EXCLUDED_FROM_V0_1'],
    status: 'FOUR_EXISTING_DRAFT_VALUES_NOT_RUNTIME'
  },
  {
    statusDomain: 'value_state',
    authority: 'FEATURE_SCHEMA_INTERNAL_CANDIDATE_ONLY',
    values: ['PRESENT', 'NOT_APPLICABLE', 'UNKNOWN'],
    status: 'INCOMPLETE_NON_PUBLIC_RUNTIME_CANDIDATE_SET'
  },
  {
    statusDomain: 'evidence_status',
    authority: 'ARCHITECTURE_SECTION_13_SOURCE_NORMATIVE',
    values: ['UNVERIFIED', 'SOURCE_CONFIRMED', 'CONTENT_VERIFIED', 'CONFLICTING', 'STALE', 'REJECTED', 'HUMAN_REVIEW_REQUIRED'],
    status: 'EXACT_SEVEN_VALUE_ENUM_PRESERVED_WITHOUT_MAPPING'
  },
  {
    statusDomain: 'lawful_basis_status',
    authority: 'ARCHITECTURE_SECTION_11_SOURCE_NORMATIVE',
    values: ['ACTIVE', 'EXPIRED', 'REVOKED', 'TERMINATED', 'SUSPENDED', 'UNDER_REVIEW'],
    status: 'EXACT_SIX_VALUE_ENUM_PRESERVED_WITHOUT_MAPPING'
  },
  {
    statusDomain: 'processing_eligibility',
    authority: 'FEATURE_SCHEMA_INTERNAL_CANDIDATE_ONLY',
    values: ['ALLOWED', 'DATA_PROCESSING_BLOCKED'],
    status: 'INCOMPLETE_NON_PUBLIC_DERIVED_CANDIDATE_SET'
  }
] as const;

export const SYNTHETIC_FEATURE_STATE_AXIS_EXACT_ENUM_BOUNDARY = [
  'evidence_status PRESERVES THE EXACT SEVEN-VALUE ARCHITECTURE §13 ENUM WITHOUT MAPPING',
  'lawful_basis_status PRESERVES THE EXACT SIX-VALUE ARCHITECTURE §11 ENUM WITHOUT MAPPING',
  'lawful_basis_status IS A SOURCE REGISTRY DOMAIN — NOT A FeatureValue AXIS',
  'DRAFT CANDIDATE TOKENS ARE NOT PROMOTED TO COMPLETE OR PUBLIC RUNTIME ENUMS'
] as const;

export const SYNTHETIC_FEATURE_STATE_AXIS_NON_COERCION = [
  'BLOCKED_PENDING_DECISION IS A DESIGN-TIME RULE STATUS ONLY',
  'PRESENT IS A VALUE APPLICABILITY CANDIDATE ONLY — NO EVIDENCE OR PROCESSING INFERENCE',
  'UNKNOWN AND NOT_APPLICABLE REMAIN DISTINCT AND NON-ADVERSE — NO ZERO, NEGATIVE, PASS, FAIL OR INELIGIBLE',
  'STALE IS AN EVIDENCE STATE ONLY — NO NEGATIVE FACT, FAILURE, REJECTION OR ROUTE',
  'DATA_PROCESSING_BLOCKED FAILS CLOSED FOR THE AFFECTED GOVERNED USE ONLY — NO AUTOMATIC INELIGIBLE, REJECTION OR GLOBAL BLOCK',
  'NO AXIS COLLAPSE, DEFAULT MAPPING, TRANSITION OR SILENT CASCADE'
] as const;

export const SYNTHETIC_FEATURE_STATE_AXIS_OPEN_CONTENT = [
  'FULL PUBLIC value_state ENUM',
  'FULL PUBLIC processing_eligibility ENUM',
  'SOURCE-TO-STATE MAPPINGS AND PRECEDENCE',
  'TRANSITIONS, CASCADE AND AFFECTED-USE GRANULARITY',
  'CONFLICT, MISSING, STALE, BLOCKED, INVALIDATION AND RECOVERY DETAILS',
  'ERROR, REASON, RETRY, ESCALATION AND OBSERVABILITY TAXONOMY',
  'SCHEMA, API, EVENT, DATABASE, STORAGE, TRANSPORT AND RUNTIME CARRIER',
  'COMPATIBILITY, MIGRATION, VERSIONING, DATA, TESTS, METRICS AND EVIDENCE',
  'FEATURE SCHEMA, POLICY, DATA CONTRACT, MANIFEST, PRODUCTION, RUNTIME, IMPLEMENTATION AND GATES'
] as const;

export const SYNTHETIC_FEATURE_STATE_AXIS_TERMINAL_TOKEN =
  'G24_SYNTHETIC_NO_RUNTIME_STATE_OR_ELIGIBILITY_ACTION_EXECUTED' as const;

export const SYNTHETIC_FEATURE_STATE_AXIS_TERMINAL_LINE =
  'NO RUNTIME ENUM, MAPPING, TRANSITION, CASCADE, VALUE COERCION, PASS, FAIL, INELIGIBLE, QUALIFICATION, RISK, SCORE, RANKING, RECOMMENDATION OR ROUTING OCCURRED' as const;
