export const SYNTHETIC_FEATURE_READINESS_MATRIX_TITLE =
  'SYNTHETIC FEATURE READINESS MATRIX — NOT PRODUCTION APPROVED' as const;

export const SYNTHETIC_FEATURE_READINESS_MATRIX_DISCLAIMER =
  'MANUAL DEV-ONLY MATRIX — DESIGN-TIME SOURCE COPY ONLY' as const;

export const SYNTHETIC_FEATURE_READINESS_MATRIX_SCOPE_LINE =
  'NO FEATURE VALUE, COMPARISON OR MATCH RESULT COMPUTED' as const;

export const SYNTHETIC_FEATURE_READINESS_MATRIX_REGIONS_IN_ORDER = [
  'READINESS CATEGORIES — SOURCE-BOUND DEFINITIONS',
  'TWENTY HARD-CONSTRAINT CANDIDATES — INDEX ONLY',
  'MIXED AND BLOCKED BOUNDARIES — NO STATUS FLATTENING',
  'PROHIBITED INFERENCES — FIXTURE COPY',
  'NON-COMPUTATION RESULT'
] as const;

export const SYNTHETIC_FEATURE_READINESS_MATRIX_CATEGORIES = [
  'READY_FOR_DRAFT',
  'READY_AS_CANDIDATE_ONLY',
  'BLOCKED_PENDING_DECISION',
  'EXCLUDED_FROM_V0_1'
] as const;

export const SYNTHETIC_FEATURE_READINESS_MATRIX_CATEGORY_COPY =
  'SOURCE-BOUND DESIGN-TIME CATEGORY — NOT RUNTIME STATE OR APPROVAL' as const;

export const SYNTHETIC_FEATURE_READINESS_MATRIX_REASON = {
  value: 'BLOCKED_PENDING_COMPATIBILITY_TABLE',
  copy: 'readiness_reason SUBTYPE OF BLOCKED_PENDING_DECISION — NOT A FIFTH STATUS'
} as const;

export const SYNTHETIC_FEATURE_READINESS_MATRIX_FEATURE_IDS = [
  'property_type_membership',
  'area_range_fit',
  'budget_fit',
  'rent_rate_fit',
  'business_category_allowed',
  'condition_acceptability',
  'timing_compatibility',
  'entrance_requirement_fit',
  'required_features_present',
  'excluded_features_absent',
  'loading_access_required_fit',
  'power_min_fit',
  'ceiling_height_min_fit',
  'parking_min_fit',
  'access_mode_hard_fit',
  'country_code_membership',
  'region_membership',
  'city_membership',
  'districts_membership',
  'floor_option_fit'
] as const;

export const SYNTHETIC_FEATURE_READINESS_MATRIX_SAFEGUARDS = [
  'ALL 20 ARE DESIGN-TIME ELIGIBILITY_HARD_CONSTRAINT_CANDIDATES — NOT APPROVED RUNTIME RULES',
  'FINAL LEGAL VERDICT IS NOT APPROVED FOR ANY OF THE 20',
  'required_evidence_level REMAINS BLOCKED_PENDING_DECISION FOR ALL 20',
  'automatic_ineligible_allowed = NO FOR ALL 20'
] as const;

export const SYNTHETIC_FEATURE_READINESS_MATRIX_MIXED_BOUNDARIES = [
  {
    ordinal: 4,
    featureId: 'rent_rate_fit',
    copy: 'QUALITATIVE VERSION/HASH DISCIPLINE ONLY — EXACT NUMERIC REPRESENTATION REMAINS BLOCKED'
  },
  {
    ordinal: 8,
    featureId: 'entrance_requirement_fit',
    copy: 'OVERALL BLOCKED_PENDING_DECISION — PARTIAL QUALITATIVE PAIRS DO NOT FLATTEN THE ROW TO READY'
  },
  {
    ordinal: 15,
    featureId: 'access_mode_hard_fit',
    copy: 'OVERALL BLOCKED_PENDING_DECISION — STRICT-EQUALITY BASELINE DOES NOT FLATTEN THE ROW TO READY'
  },
  {
    ordinal: 17,
    featureId: 'region_membership',
    copy: 'READY_AS_CANDIDATE_ONLY QUALITATIVE LITERAL-MATCH BASELINE — NOT ACTIVE RUNTIME COMPARISON'
  },
  {
    ordinal: 18,
    featureId: 'city_membership',
    copy: 'READY_AS_CANDIDATE_ONLY QUALITATIVE LITERAL-MATCH BASELINE — NOT ACTIVE RUNTIME COMPARISON'
  },
  {
    ordinal: 19,
    featureId: 'districts_membership',
    copy: 'READY_AS_CANDIDATE_ONLY QUALITATIVE LITERAL-MATCH BASELINE — NOT ACTIVE RUNTIME COMPARISON'
  },
  {
    ordinal: 20,
    featureId: 'floor_option_fit',
    copy: 'OVERALL BLOCKED_PENDING_DECISION — WILDCARD/LAND BOUNDARIES DO NOT FLATTEN THE ROW TO READY'
  }
] as const;

export const SYNTHETIC_FEATURE_READINESS_MATRIX_PROHIBITED_INFERENCES = [
  'NO STATUS BY SIMILARITY, OMISSION, TABLE POSITION OR SIBLING RULE',
  'NO RUNTIME FEATURE VALUE',
  'NO PASS, FAIL OR INCOMPATIBILITY VERDICT',
  'NO AUTOMATIC INELIGIBLE',
  'NO SCORE, CONFIDENCE, QUALIFICATION OR RISK',
  'NO RANKING, RECOMMENDATION OR ROUTING',
  'NO PROPERTY, TENANT REQUEST OR BUSINESS RECORD VALUES'
] as const;

export const SYNTHETIC_FEATURE_READINESS_MATRIX_TERMINAL_TOKEN =
  'SYNTHETIC_NO_FEATURE_COMPARISON_COMPUTED' as const;

export const SYNTHETIC_FEATURE_READINESS_MATRIX_TERMINAL_LINE =
  'NO FEATURE COMPARISON COMPUTED — NO FEATURE VALUE, PASS, FAIL, INELIGIBLE, SCORE, CONFIDENCE, QUALIFICATION, RISK, RANKING, RECOMMENDATION OR ROUTING OCCURRED' as const;
