export const G34_TITLE =
  'SYNTHETIC CRITERION-CLASS WEIGHTING QUALITATIVE POLICY EVIDENCE BOUNDARY REFERENCE — NOT PRODUCTION APPROVED' as const;

export const G34_DISCLAIMER =
  'MANUAL DEV-ONLY REFERENCE — QUALITATIVE CRITERION-CLASS POLICY AND EVIDENCE BOUNDARY ONLY' as const;

export const G34_SCOPE_LINE =
  'NO CRITERION-CLASS ASSIGNMENT, WEIGHT, RATIO, FORMULA, NORMALIZATION, THRESHOLD, SEGMENT OVERRIDE OR RUNTIME USE SELECTED' as const;

export const G34_REGIONS = [
  'SOURCE AND STATUS BOUNDARY',
  'CRITERION-CLASS WEIGHTING QUALITATIVE POLICY MATRIX',
  'ROLE AND APPROVAL SEPARATION',
  'CLASS SEMANTICS, HARD-CONSTRAINT NON-SOFTENING AND FAIL-CLOSED BOUNDARY',
  'OPEN EXACT CONTENT',
  'NON-DECISION RESULT'
] as const;

export const G34_SOURCE_BOUNDARY = [
  'SOURCE DECISION: XFR-D-025 v1.0 — PARTIALLY_RESOLVED_BOUNDARY',
  'CANONICAL IDENTITY: MSP-13 → XFR-D-025 — PRIMARY_STANDALONE',
  'INVENTORY COUNTS: 102 SOURCE KEYS / 90 CANONICAL IDS — UNCHANGED',
  'SCORING REGISTER: 18 ROWS — UNCHANGED; EVALUATION REGISTER: 17 ROWS — UNCHANGED',
  'APPROVED BOUNDARY IS QUALITATIVE ONLY: MANDATORY, DESIRABLE, NEGOTIABLE AND INFORMATIONAL SEMANTICS; LAYER SEPARATION; CONFIRMED HARD-CONSTRAINT PRECEDENCE AND NON-SOFTENING; AFFECTED-USE FAIL-CLOSED; GLOBAL-VERSUS-SEGMENT SEPARATION; IMMUTABLE FROZEN EVIDENCE; NON-COMPENSATION; AND NO AUTOMATIC ACTION',
  'EVERY EXACT ASSIGNMENT, HIERARCHY, PARTICIPATION RULE, WEIGHT, RATIO, SIGN, SCALE, FORMULA, NORMALIZATION, NUMERATOR, DENOMINATOR, DOUBLE-COUNTING TREATMENT, SEGMENT CONTENT, THRESHOLD, PRECISION, DATASET, METRIC, STATISTIC, RESULT, POLICY, MANIFEST, PRODUCTION, SCHEMA, CARRIER, RUNTIME AND IMPLEMENTATION CONTENT REMAINS OPEN',
  'IMPLEMENTATION READINESS, SYNTHETIC ACCEPTANCE AND PRODUCTION LAUNCH REMAIN BLOCKED; PACKAGE GATE IMPACT IS NONE'
] as const;

export type G34PolicyRow = {
  readonly matrixRow: string;
  readonly frozenBoundary: string;
};

export const G34_POLICY_MATRIX: readonly G34PolicyRow[] = [
  { matrixRow: 'MANDATORY_DESIRABLE_NEGOTIABLE_INFORMATIONAL_SEMANTIC_PRESERVATION', frozenBoundary: 'MANDATORY_DESIRABLE_NEGOTIABLE_INFORMATIONAL_SEMANTIC_PRESERVATION' },
  { matrixRow: 'CRITERION_CLASS_IS_NOT_FEATURE_WEIGHT_HARD_CONSTRAINT_EVIDENCE_CONFIDENCE_RISK_QUALIFICATION_OR_PRIORITY_LAYER', frozenBoundary: 'CRITERION_CLASS_IS_NOT_FEATURE_WEIGHT_HARD_CONSTRAINT_EVIDENCE_CONFIDENCE_RISK_QUALIFICATION_OR_PRIORITY_LAYER' },
  { matrixRow: 'CONFIRMED_HARD_CONSTRAINT_PRE_SCORING_PRECEDENCE_AND_NON_SOFTENING', frozenBoundary: 'CONFIRMED_HARD_CONSTRAINT_PRE_SCORING_PRECEDENCE_AND_NON_SOFTENING' },
  { matrixRow: 'MANDATORY_LABEL_ALONE_CREATES_NO_HARD_CONSTRAINT_INELIGIBLE_OR_REJECTION', frozenBoundary: 'MANDATORY_LABEL_ALONE_CREATES_NO_HARD_CONSTRAINT_INELIGIBLE_OR_REJECTION' },
  { matrixRow: 'DESIRABLE_ABSENCE_CREATES_NO_AUTOMATIC_REJECTION', frozenBoundary: 'DESIRABLE_ABSENCE_CREATES_NO_AUTOMATIC_REJECTION' },
  { matrixRow: 'NEGOTIABLE_REMAINS_SCENARIO_ONLY_UNTIL_HUMAN_CONFIRMATION', frozenBoundary: 'NEGOTIABLE_REMAINS_SCENARIO_ONLY_UNTIL_HUMAN_CONFIRMATION' },
  { matrixRow: 'INFORMATIONAL_CLASS_IDENTITY_PRESERVED_WEIGHTING_APPLICABILITY_OPEN', frozenBoundary: 'INFORMATIONAL_CLASS_IDENTITY_PRESERVED_WEIGHTING_APPLICABILITY_OPEN' },
  { matrixRow: 'AFFECTED_USE_FAIL_CLOSED_WITHOUT_DEFAULTS_OR_NEGATIVE_FACTS', frozenBoundary: 'AFFECTED_USE_FAIL_CLOSED_WITHOUT_DEFAULTS_OR_NEGATIVE_FACTS' },
  { matrixRow: 'GLOBAL_VS_SEGMENT_SPECIFIC_WEIGHTING_SEPARATION_XFR_D_018_AND_XFR_D_M5_INDEPENDENT', frozenBoundary: 'GLOBAL_VS_SEGMENT_SPECIFIC_WEIGHTING_SEPARATION_XFR_D_018_AND_XFR_D_M5_INDEPENDENT' },
  { matrixRow: 'IMMUTABLE_VERSION_HASH_FROZEN_EVIDENCE_NON_COMPENSATION_AND_REPRODUCIBILITY_PREREQUISITES', frozenBoundary: 'IMMUTABLE_VERSION_HASH_FROZEN_EVIDENCE_NON_COMPENSATION_AND_REPRODUCIBILITY_PREREQUISITES' },
  { matrixRow: 'SYNTHETIC_ONLY_EVIDENCE_CREATES_NO_PRODUCTION_CLAIM', frozenBoundary: 'SYNTHETIC_ONLY_EVIDENCE_CREATES_NO_PRODUCTION_CLAIM' },
  { matrixRow: 'PARTIALLY_RESOLVED_BOUNDARY_EXACT_CONTENT_OPEN_AND_NO_FULL_RESOLUTION', frozenBoundary: 'PARTIALLY_RESOLVED_BOUNDARY_EXACT_CONTENT_OPEN_AND_NO_FULL_RESOLUTION' }
] as const;

export const G34_ROLE_SEPARATION = [
  'XFR-D-025 GOVERNANCE OWNER: AI + PRODUCT — HUMAN-APPROVED CANDIDATE-DERIVED AND NOT SOURCE_NORMATIVE FOR THE STANDALONE DECISION',
  'SCORING ARTIFACT OWNER: Chief AI Architect + PRODUCT',
  'MANDATORY APPROVERS: Chief AI Architect + LEGAL + DEVELOPMENT',
  'EVIDENCE/TECHNICAL-PROCEDURE OWNER: AI + DEVELOPMENT — NO UNILATERAL SEMANTIC, VALUE, POLICY, PRODUCTION, RELEASE OR IMPLEMENTATION AUTHORITY',
  'XFR-D-M5 RETAINS INDEPENDENT SOURCE_NORMATIVE AI + PRODUCT AUTHORITY FOR ARCHITECTURE §37 QUESTION №3',
  'G34 ASSIGNS NO NEW OWNER, WIDENS NO AUTHORITY AND CONFLATES NO OWNER, APPROVER, EVIDENCE PREPARER OR RUNTIME WRITER'
] as const;

export const G34_CLASS_AND_HARD_CONSTRAINT_BOUNDARY = [
  'MANDATORY, DESIRABLE, NEGOTIABLE AND INFORMATIONAL KEEP THEIR SOURCE MEANINGS AND CREATE NO NUMERIC OR ORDINAL HIERARCHY',
  'CRITERION CLASS IS NOT FEATURE WEIGHT/FIT, HARD CONSTRAINT/ELIGIBILITY, EVIDENCE/CONFIDENCE, RISK, QUALIFICATION, PRIORITY SCORE, RANKING OR PRESENTATION',
  'A SEPARATELY APPROVED, APPLICABLE AND EVIDENCED CONFIRMED HARD-CONSTRAINT VIOLATION IS HANDLED BEFORE SCORING AND CANNOT BE SOFTENED, AVERAGED OR COMPENSATED',
  'THE MANDATORY LABEL ALONE CREATES NO HARD CONSTRAINT, INELIGIBLE RESULT, REJECTION OR QUALIFICATION ROUTE',
  'DESIRABLE ABSENCE CREATES NO AUTOMATIC REJECTION; NEGOTIABLE CONTENT REMAINS SCENARIO-ONLY UNTIL HUMAN CONFIRMATION; INFORMATIONAL IDENTITY IS PRESERVED'
] as const;

export const G34_FAIL_CLOSED_AND_EVIDENCE = [
  'MISSING, UNKNOWN, STALE, CONFLICTING, AMBIGUOUS, INCOMPATIBLE, EXPIRED, REVOKED OR UNAUTHORIZED CLASS, SOURCE, EVIDENCE, VERSION/HASH, LAWFUL BASIS OR PARTICIPATION STATE BLOCKS ONLY THE AFFECTED USE',
  'NO DEFAULT, EQUAL, AVERAGE, ZERO, NEUTRAL, NEAREST, HEURISTIC, AI-INFERRED OR PROXY-IMPUTED CLASS, WEIGHT, RATIO OR PARTICIPATION RULE IS CREATED',
  'FAILURE CREATES NO NEGATIVE BUSINESS FACT, HARD CONSTRAINT, INELIGIBLE RESULT, REJECTION, RISK CONCLUSION, RANK, ROUTE, SAFE REASON OR DISPLAY PERMISSION',
  'GLOBAL, SEGMENT-SPECIFIC AND PER-FEATURE WEIGHTING REMAIN SEPARATE; SEGMENT MEMBERSHIP CANNOT BE GUESSED OR PROXY-IMPUTED',
  'IMMUTABLE VERSION/HASH-BOUND FROZEN EVIDENCE, BASELINE-FIRST HISTORY, TUNING/FINAL ISOLATION, PREREGISTRATION, COMPATIBLE COMPARISON, SEPARATE REPORTING AND NON-COMPENSATION ARE PREREQUISITES, NOT APPROVALS',
  'SYNTHETIC EVIDENCE CREATES NO PRODUCTION CLAIM; EXACT REPLAY PROVES REPRODUCIBILITY ONLY; NO RESULT AUTOMATICALLY CHANGES POLICY, MODEL, RANKING, ROUTING, RUNTIME, RELEASE OR GATE'
] as const;

export const G34_OPEN_CONTENT = [
  'CRITERION-CLASS ASSIGNMENTS, PARTICIPATION, HIERARCHY AND APPLICABILITY',
  'WEIGHTS, RATIOS, SIGNS, SCALES, BOUNDS, DEFAULTS, MINIMUMS, MAXIMUMS AND THRESHOLDS',
  'FORMULA, NORMALIZATION, NUMERATOR, DENOMINATOR, ACTIVE-WEIGHT, MISSING-VALUE AND DOUBLE-COUNTING TREATMENT',
  'GLOBAL, PER-DIMENSION, PER-FEATURE, PER-CLASS, PER-SIDE, PER-SEGMENT AND PER-INTERSECTION WEIGHTING',
  'SEGMENT UNIVERSE, INTERSECTIONS, MEMBERSHIP, PROTECTED/PROXY CLASSIFICATION AND LAWFUL BASIS',
  'PRECISION, ROUNDING, EQUALITY, TOLERANCE, SERIALIZATION AND REPLAY MECHANICS',
  'DATASET, SAMPLE, SPLIT, SEED, LABELS, ADJUDICATION, METRICS, TARGETS, BASELINES, INTERVALS, WINDOWS, TESTS, RESULTS AND VERDICT',
  'POLICY, MANIFEST, PRODUCTION DATA, SCHEMA, CARRIER, RBAC, RUNTIME, MONITORING, ROLLBACK, IMPLEMENTATION AND GATES'
] as const;

export const G34_PROHIBITED_SURROGATES = [
  'NO 0.5/0.5 NEUTRAL BASELINE, 100-CAMPAIGN PILOT CAP OR CAMPAIGN-TO-QUALIFIED 40%/25% TARGET MAY BECOME A CLASS WEIGHT, RATIO, THRESHOLD OR ACCEPTANCE TARGET',
  'SYNTHETIC OUTPUT, LIBRARY DEFAULT, CURRENT IMPLEMENTATION BEHAVIOR, AGGREGATE IMPROVEMENT OR MAJORITY RESULT CANNOT SUBSTITUTE FOR OPEN AUTHORITY OR EVIDENCE',
  'NO CLASS, SEGMENT OR INTERSECTION FAILURE MAY BE HIDDEN BY FAVORABLE AGGREGATE EVIDENCE'
] as const;

export const G34_NON_DECISION_RESULT =
  'G34 NON-DECISION RESULT: NO CRITERION-CLASS ASSIGNMENT, HIERARCHY, PARTICIPATION RULE, WEIGHT, RATIO, SIGN, SCALE, FORMULA, NORMALIZATION, NUMERATOR, DENOMINATOR, DOUBLE-COUNTING TREATMENT, SEGMENT OVERRIDE, THRESHOLD, PRECISION, DATASET, METRIC, STATISTIC, RESULT, POLICY, MANIFEST, PRODUCTION-DATA USE, SCHEMA, CARRIER, RUNTIME OR IMPLEMENTATION IS SELECTED, CALCULATED OR APPROVED. XFR-D-025 v1.0 REMAINS PARTIALLY_RESOLVED_BOUNDARY WITH CANONICAL IDENTITY MSP-13 TO XFR-D-025 PRIMARY_STANDALONE. XFR-D-M5 REMAINS INDEPENDENT. SYNTHETIC EVIDENCE CREATES NO PRODUCTION CLAIM, GATE IMPACT IS NONE, AND ALL THREE GOVERNANCE GATES REMAIN BLOCKED.' as const;

export const G34_TERMINAL_TOKEN =
  'G34_SYNTHETIC_NO_CRITERION_CLASS_ASSIGNMENT_WEIGHT_RATIO_FORMULA_NORMALIZATION_THRESHOLD_SEGMENT_OVERRIDE_OR_RUNTIME_USE_SELECTED' as const;

export const G34_TERMINAL_LINE =
  'NO CRITERION-CLASS ASSIGNMENT, WEIGHT, RATIO, FORMULA, NORMALIZATION, THRESHOLD, SEGMENT OVERRIDE, DATA, PRODUCTION, RUNTIME OR IMPLEMENTATION ACTION OCCURRED' as const;
