export const G44_TITLE =
  'SYNTHETIC QUALIFICATION QUALITATIVE-PRECEDENCE REFERENCE — NOT PRODUCTION APPROVED' as const;

export const G44_DISCLAIMER =
  'MANUAL DEV-ONLY REFERENCE — QUALITATIVE PRECEDENCE IS NOT NUMERIC SEVERITY, REASON-CATALOG ORDER OR RUNTIME ALGORITHM APPROVAL' as const;

export const G44_SCOPE_LINE =
  'NO NUMERIC THRESHOLD, SEVERITY REGISTRY, REASON-CATALOG ORDER, RUNTIME ALGORITHM, POLICY OR RUNTIME USE SELECTED' as const;

export const G44_REGIONS = [
  'SOURCE AND STATUS BOUNDARY',
  'QUALITATIVE PRECEDENCE HIERARCHY',
  'NON-COMPENSATION BOUNDARY',
  'MULTI-CAUSE AND PRIMARY-REASON SEPARATION',
  'OPEN EXACT CONTENT',
  'NON-DECISION RESULT'
] as const;

export const G44_SOURCE_BOUNDARY = [
  'SOURCE DECISION: XFR-D-033 v1.0 — APPROVED QUALITATIVE PRECEDENCE — numeric thresholds and reason catalog remain OPEN',
  'CANONICAL IDENTITY: MQP-04 → XFR-D-033 — PRIMARY_STANDALONE',
  'INVENTORY COUNTS: 102 SOURCE KEYS / 90 CANONICAL IDS — UNCHANGED; QUALIFICATION REGISTER REMAINS 20 ROWS',
  'APPROVED BOUNDARY ONLY: DETERMINISTIC FAIL-CLOSED QUALITATIVE ROUTE PRECEDENCE, NON-COMPENSATION AND ALL-CAUSE PRESERVATION',
  'QUALIFICATION SEMANTIC OWNER: Chief AI Architect + PRODUCT; MANDATORY APPROVERS: LEGAL + DEVELOPMENT; AI REMAINS CONSULTED',
  'IMPLEMENTATION READINESS, SYNTHETIC ACCEPTANCE AND PRODUCTION LAUNCH REMAIN BLOCKED; PACKAGE GATE IMPACT IS NONE'
] as const;

export type G44BoundaryRow = { readonly matrixRow: string; readonly frozenBoundary: string };

export const G44_BOUNDARY_MATRIX: readonly G44BoundaryRow[] = [
  { matrixRow: 'PRIMARY_STANDALONE_IDENTITY_AND_APPROVED_QUALITATIVE_PRECEDENCE_PRESERVED_WITH_NUMERIC_THRESHOLDS_AND_REASON_CATALOG_OPEN', frozenBoundary: 'PRIMARY_STANDALONE_IDENTITY_AND_APPROVED_QUALITATIVE_PRECEDENCE_PRESERVED_WITH_NUMERIC_THRESHOLDS_AND_REASON_CATALOG_OPEN' },
  { matrixRow: 'CONFIRMED_ELIGIBILITY_INELIGIBLE_WITH_COMPLETE_SIX_PART_EVIDENCE_HAS_HIGHEST_PRECEDENCE_AND_ROUTES_TO_REJECTED_BY_MATCHING', frozenBoundary: 'CONFIRMED_ELIGIBILITY_INELIGIBLE_WITH_COMPLETE_SIX_PART_EVIDENCE_HAS_HIGHEST_PRECEDENCE_AND_ROUTES_TO_REJECTED_BY_MATCHING' },
  { matrixRow: 'MANDATORY_HUMAN_REVIEW_CAUSE_ROUTES_TO_HUMAN_REVIEW_REQUIRED_ONLY_WHEN_NO_CONFIRMED_INELIGIBLE_EXISTS', frozenBoundary: 'MANDATORY_HUMAN_REVIEW_CAUSE_ROUTES_TO_HUMAN_REVIEW_REQUIRED_ONLY_WHEN_NO_CONFIRMED_INELIGIBLE_EXISTS' },
  { matrixRow: 'UNRESOLVED_VERIFICATION_NEED_MISSING_UNKNOWN_OR_INSUFFICIENT_EVIDENCE_ROUTES_TO_NEEDS_VERIFICATION_ONLY_WHEN_NO_HIGHER_CLASS_EXISTS', frozenBoundary: 'UNRESOLVED_VERIFICATION_NEED_MISSING_UNKNOWN_OR_INSUFFICIENT_EVIDENCE_ROUTES_TO_NEEDS_VERIFICATION_ONLY_WHEN_NO_HIGHER_CLASS_EXISTS' },
  { matrixRow: 'QUALIFIED_HYPOTHESIS_IS_PERMITTED_ONLY_WHEN_ALL_THREE_HIGHER_CLASSES_ARE_ABSENT_AND_ALL_ARCHITECTURE_SECTION_18_1_QUALITATIVE_CONDITIONS_ARE_MET', frozenBoundary: 'QUALIFIED_HYPOTHESIS_IS_PERMITTED_ONLY_WHEN_ALL_THREE_HIGHER_CLASSES_ARE_ABSENT_AND_ALL_ARCHITECTURE_SECTION_18_1_QUALITATIVE_CONDITIONS_ARE_MET' },
  { matrixRow: 'STALE_IS_ORTHOGONAL_UNDER_XFR_D_038_AND_IS_NOT_A_ROUTING_RESULT_OR_FIFTH_PRECEDENCE_LEVEL', frozenBoundary: 'STALE_IS_ORTHOGONAL_UNDER_XFR_D_038_AND_IS_NOT_A_ROUTING_RESULT_OR_FIFTH_PRECEDENCE_LEVEL' },
  { matrixRow: 'SCORE_RANK_CONFIDENCE_OR_OTHER_FAVORABLE_SIGNAL_CANNOT_COMPENSATE_FOR_A_HIGHER_PRECEDENCE_CLASS', frozenBoundary: 'SCORE_RANK_CONFIDENCE_OR_OTHER_FAVORABLE_SIGNAL_CANNOT_COMPENSATE_FOR_A_HIGHER_PRECEDENCE_CLASS' },
  { matrixRow: 'PRECEDENCE_SELECTS_THE_FINAL_ROUTE_BUT_NEVER_DELETES_OTHER_APPLICABLE_CAUSES_OR_EVIDENCE_REFERENCES', frozenBoundary: 'PRECEDENCE_SELECTS_THE_FINAL_ROUTE_BUT_NEVER_DELETES_OTHER_APPLICABLE_CAUSES_OR_EVIDENCE_REFERENCES' },
  { matrixRow: 'PRIMARY_REASON_REMAINS_A_SUMMARY_FROM_THE_ROUTE_DETERMINING_CLASS_UNDER_XFR_D_040', frozenBoundary: 'PRIMARY_REASON_REMAINS_A_SUMMARY_FROM_THE_ROUTE_DETERMINING_CLASS_UNDER_XFR_D_040' },
  { matrixRow: 'INCIDENTAL_IDENTIFIER_FILE_STORAGE_MANIFEST_CROSSWALK_DISCOVERY_SQL_MAPPING_ORDER_OR_MULTIPLICITY_HAS_NO_SEMANTIC_PRIORITY', frozenBoundary: 'INCIDENTAL_IDENTIFIER_FILE_STORAGE_MANIFEST_CROSSWALK_DISCOVERY_SQL_MAPPING_ORDER_OR_MULTIPLICITY_HAS_NO_SEMANTIC_PRIORITY' },
  { matrixRow: 'NUMERIC_THRESHOLDS_ORDINAL_SEVERITY_REGISTRY_EXACT_REASON_CATALOG_ORDER_PRIMARY_REASON_REPRESENTATION_AND_RUNTIME_ALGORITHM_REMAIN_OPEN', frozenBoundary: 'NUMERIC_THRESHOLDS_ORDINAL_SEVERITY_REGISTRY_EXACT_REASON_CATALOG_ORDER_PRIMARY_REASON_REPRESENTATION_AND_RUNTIME_ALGORITHM_REMAIN_OPEN' },
  { matrixRow: 'GATE_IMPACT_NONE_AND_IMPLEMENTATION_READINESS_SYNTHETIC_ACCEPTANCE_AND_PRODUCTION_LAUNCH_REMAIN_BLOCKED', frozenBoundary: 'GATE_IMPACT_NONE_AND_IMPLEMENTATION_READINESS_SYNTHETIC_ACCEPTANCE_AND_PRODUCTION_LAUNCH_REMAIN_BLOCKED' }
] as const;

export const G44_PRECEDENCE_HIERARCHY = [
  '1 — CONFIRMED ELIGIBILITY INELIGIBLE WITH COMPLETE SIX-PART ARCHITECTURE §14 EVIDENCE → REJECTED_BY_MATCHING',
  '2 — MANDATORY HUMAN-REVIEW CAUSE: CRITICAL CONFLICT, CRITICAL UNRESOLVED RISK OR LEGAL/RIGHTS AMBIGUITY → HUMAN_REVIEW_REQUIRED ONLY ABSENT CONFIRMED INELIGIBLE',
  '3 — UNRESOLVED VERIFICATION NEED, MISSING/UNKNOWN OR INSUFFICIENT EVIDENCE → NEEDS_VERIFICATION ONLY ABSENT A HIGHER CLASS',
  '4 — QUALIFIED_HYPOTHESIS ONLY WHEN ALL THREE HIGHER CLASSES ARE ABSENT AND ALL QUALITATIVE ARCHITECTURE §18.1 CONDITIONS ARE MET',
  'STALE REMAINS ORTHOGONAL UNDER XFR-D-038; IT IS NOT A ROUTING RESULT OR FIFTH PRECEDENCE LEVEL'
] as const;

export const G44_NON_COMPENSATION = [
  'SCORE CANNOT OFFSET, DOWNGRADE OR OVERRIDE A HIGHER-PRECEDENCE CLASS',
  'RANK CANNOT OFFSET, DOWNGRADE OR OVERRIDE A HIGHER-PRECEDENCE CLASS',
  'CONFIDENCE CANNOT OFFSET, DOWNGRADE OR OVERRIDE A HIGHER-PRECEDENCE CLASS',
  'ANY OTHER FAVORABLE SIGNAL CANNOT COMPENSATE FOR CONFIRMED HARD-CONSTRAINT FAILURE, MANDATORY HUMAN REVIEW OR UNRESOLVED REQUIRED VERIFICATION',
  'CAUSE COUNT, MULTIPLICITY OR AGGREGATION DOES NOT CREATE A NUMERIC SEVERITY OR A DIFFERENT ROUTE',
  'NO LOWER CLASS OR FAVORABLE SIGNAL CAN PROMOTE THE RESULT TO QUALIFIED_HYPOTHESIS'
] as const;

export const G44_MULTI_CAUSE_SEPARATION = [
  'PRECEDENCE SELECTS ONE FINAL ROUTE BUT NEVER DELETES OTHER APPLICABLE CAUSES OR EVIDENCE REFERENCES',
  'PRIMARY REASON REMAINS A SUMMARY ONLY FROM THE ROUTE-DETERMINING PRECEDENCE CLASS UNDER XFR-D-040',
  'SAME-CLASS SEMANTIC ORDER AND PRIMARY-REASON REPRESENTATION REMAIN OPEN',
  'IDENTIFIER, FILE, STORAGE, MANIFEST, CROSSWALK, DISCOVERY, SQL OR MAPPING ORDER HAS NO SEMANTIC PRIORITY',
  'MULTIPLICITY HAS NO SEMANTIC PRIORITY AND CANNOT SELECT A PRIMARY REASON',
  'XFR-D-039 v1.1 DOES NOT RECALCULATE THE ROUTE OR DROP CAUSES; CATALOG AND CROSSWALK CONTENT REMAIN INDEPENDENT'
] as const;

export const G44_OPEN_CONTENT = [
  'NUMERIC THRESHOLDS, CUTOFFS, COMPARATORS AND CALIBRATION',
  'ORDINAL SEVERITY REGISTRY, VALUES, WEIGHTS AND AGGREGATION',
  'REASON-CATALOG IDENTIFIERS, CODES, VALUES, MEMBERSHIP AND EXACT ORDER',
  'SAME-CLASS SEMANTIC ORDER AND PRIMARY-REASON REPRESENTATION',
  'RUNTIME PRECEDENCE ALGORITHM, DATA STRUCTURES AND TIE HANDLING',
  'ENUM, FIELD, CARRIER, SCHEMA, API, DB, EVENT AND TRANSPORT REPRESENTATION',
  'VERSIONING, COMPATIBILITY, MIGRATION, SUPERSESSION AND ROLLBACK',
  'EVIDENCE, PROVENANCE, REPLAY, AUDIT, MONITORING, TTL, EXPIRY AND RECALCULATION',
  'QUALIFICATION POLICY, DATA CONTRACTS, MANIFEST, DATASET, PRODUCTION, RUNTIME, IMPLEMENTATION, RELEASE AND GATES'
] as const;

export const G44_INDEPENDENT_BOUNDARIES = [
  'XFR-D-032 ELIGIBILITY-TO-QUALIFICATION MAPPING REMAINS INDEPENDENT',
  'XFR-D-038 STALE ORTHOGONALITY AND XFR-D-039 v1.1 CATALOG/CROSSWALK TOPOLOGY REMAIN INDEPENDENT',
  'XFR-D-040 ALL-CAUSE AND PRIMARY-REASON AUTHORITY REMAINS INDEPENDENT',
  'XFR-D-041 REVIEW REQUEST, XFR-D-043 COMPATIBILITY AND XFR-D-044 SAFE PRESENTATION REMAIN INDEPENDENT',
  'XFR-D-055 RISK INTERFACE AND MERGED XFR-D-M2 REMAIN INDEPENDENT; NO SIBLING BOUNDARY IS REOPENED, ABSORBED, SUPERSEDED OR APPROVED BY G44'
] as const;

export const G44_NON_DECISION_RESULT =
  'G44 NON-DECISION RESULT: NO NUMERIC THRESHOLD, CUTOFF, COMPARATOR, SEVERITY VALUE, WEIGHT, AGGREGATION, REASON-CATALOG ENTRY OR ORDER, PRIMARY-REASON REPRESENTATION, RUNTIME ALGORITHM, DATA STRUCTURE, ENUM, FIELD, CARRIER, SCHEMA, API, DB, EVENT, TRANSPORT, QUALIFICATION POLICY, DATA CONTRACTS CHANGE, MANIFEST, DATASET, EVIDENCE VERDICT, PRODUCTION-DATA USE, RUNTIME, MONITORING, IMPLEMENTATION OR RELEASE IS SELECTED, CALCULATED OR APPROVED. XFR-D-033 v1.0 REMAINS APPROVED QUALITATIVE PRECEDENCE — NUMERIC THRESHOLDS AND REASON CATALOG REMAIN OPEN; MQP-04 REMAINS PRIMARY_STANDALONE. GATE IMPACT IS NONE, AND ALL THREE GOVERNANCE GATES REMAIN BLOCKED.' as const;

export const G44_TERMINAL_TOKEN =
  'G44_SYNTHETIC_NO_NUMERIC_THRESHOLD_SEVERITY_REGISTRY_REASON_CATALOG_ORDER_RUNTIME_ALGORITHM_POLICY_OR_IMPLEMENTATION_AUTHORITY_ESTABLISHED' as const;

export const G44_TERMINAL_LINE =
  'NO NUMERIC THRESHOLD, SEVERITY REGISTRY, REASON-CATALOG ORDER, RUNTIME ALGORITHM, POLICY, PRODUCTION, RUNTIME OR IMPLEMENTATION ACTION OCCURRED' as const;
