export const SYNTHETIC_DEAL_REHEARSAL_BOARD_TITLE =
  'SYNTHETIC DEAL REHEARSAL BOARD — NOT PRODUCTION APPROVED' as const;

export const SYNTHETIC_DEAL_REHEARSAL_BOARD_DISCLAIMER =
  'MANUAL DEV-ONLY REHEARSAL — NO DEAL EXECUTION' as const;

export const SYNTHETIC_DEAL_REHEARSAL_BOARD_CHAIN_WARNING =
  'SEQUENCE SHOWN AT ONCE — NOT A STEPPER — NOT PROGRESSION' as const;

export const SYNTHETIC_DEAL_REHEARSAL_BOARD_CO_DISPLAY_WARNING =
  'CO-DISPLAY ONLY — NOT COMPARED OR MATCHED' as const;

export const SYNTHETIC_DEAL_REHEARSAL_BOARD_PAIR_WARNING =
  'FIXTURE ONLY — NOT MATCHED OR RANKED' as const;

export const SYNTHETIC_DEAL_REHEARSAL_BOARD_FIXTURE_LABEL =
  'PRE-AUTHORED SYNTHETIC FIXTURE — NOT COMPUTED' as const;

export const SYNTHETIC_DEAL_REHEARSAL_BOARD_SELECTION_DISCLAIMER =
  'UI REHEARSAL SELECTION ONLY — NOT APPROVAL' as const;

export const SYNTHETIC_DEAL_REHEARSAL_BOARD_NON_OCCURRENCE =
  'NO MATCH, SCORE, CONFIDENCE, QUALIFICATION, RISK, RANKING, CONTACT, DEAL OR OUTCOME OCCURRED' as const;

export const SYNTHETIC_DEAL_REHEARSAL_BOARD_NON_OCCURRENCE_TOKEN =
  'SYNTHETIC_NO_DEAL_EXECUTED' as const;

export const SYNTHETIC_DEAL_REHEARSAL_BOARD_CONTROLS_ARIA_LABEL =
  'SYNTHETIC DEAL REHEARSAL BOARD CONTROLS' as const;

export const SYNTHETIC_DEAL_REHEARSAL_BOARD_DISPOSITION_GROUP_ARIA_LABEL =
  'HUMAN REHEARSAL DISPOSITION' as const;

export const SYNTHETIC_DEAL_REHEARSAL_BOARD_RESET = 'RESET' as const;

export const SYNTHETIC_DEAL_REHEARSAL_BOARD_REHEARSAL_CHOICES = [
  'REHEARSE INTEREST',
  'REHEARSE HOLD'
] as const;

export const SYNTHETIC_DEAL_REHEARSAL_BOARD_CO_DISPLAY_REGION = {
  accessibleName: 'OWNER-SIDE NEED AND TENANT-SIDE CANDIDATE',
  ownerSide: {
    accessibleName: 'OWNER-SIDE NEED',
    line: 'OWNER-SIDE NEED — SYNTHETIC_FIXTURE_PARTY_A'
  },
  tenantSide: {
    accessibleName: 'TENANT-SIDE CANDIDATE',
    line: 'TENANT-SIDE CANDIDATE — SYNTHETIC_FIXTURE_PARTY_B'
  }
} as const;

export const SYNTHETIC_DEAL_REHEARSAL_BOARD_CHAIN_REGION_ARIA_LABEL =
  'END-TO-END REHEARSAL CHAIN — SHOWN AT ONCE' as const;

export const SYNTHETIC_DEAL_REHEARSAL_BOARD_CHAIN_NODES = [
  {
    accessibleName: 'STAGE NODE 1 — TEST DEAL TOKEN',
    lines: ['TEST DEAL TOKEN — SYNTHETIC_TEST_DEAL_A']
  },
  {
    accessibleName: 'STAGE NODE 2 — CAMPAIGN PREVIEW',
    lines: [
      'CAMPAIGN PREVIEW — SYNTHETIC_CAMPAIGN_PREVIEW_A',
      'PREVIEW ONLY — NOT LAUNCHED'
    ]
  },
  {
    accessibleName: 'STAGE NODE 3 — FIXTURE PAIR',
    lines: [
      'SYNTHETIC_FIXTURE_PARTY_A + SYNTHETIC_FIXTURE_PARTY_B',
      SYNTHETIC_DEAL_REHEARSAL_BOARD_PAIR_WARNING
    ]
  },
  {
    accessibleName: 'STAGE NODE 4 — SAFE PRESENTATION',
    lines: ['SAFE PRESENTATION — SYNTHETIC_SAFE_PRESENTATION_A']
  },
  {
    accessibleName: 'STAGE NODE 5 — HUMAN REHEARSAL DISPOSITION',
    lines: ['HUMAN REHEARSAL DISPOSITION REQUIRED']
  },
  {
    accessibleName: 'STAGE NODE 6 — NON-OCCURRENCE RESULT',
    lines: [
      SYNTHETIC_DEAL_REHEARSAL_BOARD_NON_OCCURRENCE_TOKEN,
      SYNTHETIC_DEAL_REHEARSAL_BOARD_NON_OCCURRENCE
    ]
  }
] as const;

export const SYNTHETIC_DEAL_REHEARSAL_BOARD_FIXTURE_REGION_ARIA_LABEL =
  'PRE-AUTHORED SYNTHETIC FIXTURE' as const;

export const SYNTHETIC_DEAL_REHEARSAL_BOARD_FIXTURE_ROWS = [
  'TEST DEAL TOKEN — SYNTHETIC_TEST_DEAL_A',
  'CAMPAIGN PREVIEW — SYNTHETIC_CAMPAIGN_PREVIEW_A',
  'SAFE PRESENTATION — SYNTHETIC_SAFE_PRESENTATION_A'
] as const;

export const SYNTHETIC_DEAL_REHEARSAL_BOARD_SAFE_PRESENTATION_REGION_ARIA_LABEL =
  'SAFE PRESENTATION' as const;

export const SYNTHETIC_DEAL_REHEARSAL_BOARD_BOUNDARY_PANEL_REGION_ARIA_LABEL =
  'WHAT THIS BOARD IS NOT' as const;

export const SYNTHETIC_DEAL_REHEARSAL_BOARD_BOUNDARY_PANEL_TITLE =
  'WHAT THIS BOARD IS NOT — FIXTURE COPY' as const;

export const SYNTHETIC_DEAL_REHEARSAL_BOARD_BOUNDARY_PANEL_ADJACENT_LINE =
  'FIXTURE COPY — NOT A STATUS CLAIM' as const;

export const SYNTHETIC_DEAL_REHEARSAL_BOARD_BOUNDARY_PANEL_ROWS = [
  'NOT A MATCH',
  'NOT A SCORE OR CONFIDENCE',
  'NOT A QUALIFICATION OR RISK DECISION',
  'NOT A RANKING OR RECOMMENDATION',
  'NOT A CONTACT, CAMPAIGN LAUNCH, DEAL OR OUTCOME',
  'NOT PRODUCTION APPROVED'
] as const;

export const SYNTHETIC_DEAL_REHEARSAL_BOARD_NON_OCCURRENCE_REGION_ARIA_LABEL =
  'NON-OCCURRENCE RESULT' as const;

export const SYNTHETIC_DEAL_REHEARSAL_BOARD_FLOW_TOKENS_IN_ORDER = [
  'SYNTHETIC_TEST_DEAL_A',
  'SYNTHETIC_CAMPAIGN_PREVIEW_A',
  'SYNTHETIC_FIXTURE_PARTY_A',
  'SYNTHETIC_FIXTURE_PARTY_B',
  'SYNTHETIC_SAFE_PRESENTATION_A',
  'SYNTHETIC_HEADING',
  'SYNTHETIC_MESSAGE',
  'SYNTHETIC_NO_DEAL_EXECUTED'
] as const;

export type SyntheticDealRehearsalBoardRehearsalChoice =
  (typeof SYNTHETIC_DEAL_REHEARSAL_BOARD_REHEARSAL_CHOICES)[number];
