export const G35_TITLE =
  'SYNTHETIC BOUNDED PROBABILISTIC REPLAY QUALITATIVE GOVERNANCE REFERENCE — NOT PRODUCTION APPROVED' as const;

export const G35_DISCLAIMER =
  'MANUAL DEV-ONLY REFERENCE — QUALITATIVE REPLAY GOVERNANCE AND EVIDENCE BOUNDARY ONLY' as const;

export const G35_SCOPE_LINE =
  'NO REPLAY TOLERANCE, ERROR METRIC, REASON INVARIANT, MODE SELECTION, POLICY OR RUNTIME USE SELECTED' as const;

export const G35_REGIONS = [
  'SOURCE AND STATUS BOUNDARY',
  'REPLAY-GOVERNANCE QUALITATIVE MATRIX',
  'ROLE AND ARTIFACT-OWNER SEPARATION',
  'DETERMINISTIC, RECORDED AND BOUNDED REPLAY SEPARATION',
  'OPEN EXACT CONTENT',
  'NON-DECISION RESULT'
] as const;

export const G35_SOURCE_BOUNDARY = [
  'SOURCE DECISION: XFR-D-M4 v1.0 — PARTIALLY_RESOLVED_BOUNDARY',
  'CANONICAL MERGED IDENTITY: EP-10 + MRP-11 + MQP-15 + MSP-14 → XFR-D-M4 — ALL FOUR SOURCE KEYS REMAIN PRIMARY_MERGED_MEMBER',
  'INVENTORY COUNTS: 102 SOURCE KEYS / 90 CANONICAL IDS — UNCHANGED',
  'APPROVED BOUNDARY IS QUALITATIVE ONLY: DETERMINISTIC EXACT PROTECTION; RECORDED-VERSUS-BOUNDED SEPARATION; ADVISORY-ONLY PROBABILISTIC OUTPUT; CLOSED CANDIDATE DISCIPLINE; AFFECTED-USE FAIL-CLOSED; NON-COMPENSATION; FROZEN EVIDENCE; HISTORICAL INTEGRITY; AND NO AUTOMATIC ACTION',
  'EVERY TOLERANCE, ERROR METRIC, REASON INVARIANT, COMPONENT APPLICABILITY, MODE SELECTION, AGGREGATION, ARTIFACT SCHEMA, DATASET, STATISTIC, POLICY, PRODUCTION-DATA USE, SCHEMA, CARRIER, API, DB, EVENT, RUNTIME AND IMPLEMENTATION CONTENT REMAINS OPEN',
  'IMPLEMENTATION READINESS, SYNTHETIC ACCEPTANCE AND PRODUCTION LAUNCH REMAIN BLOCKED; PACKAGE GATE IMPACT IS NONE'
] as const;

export type G35GovernanceRow = {
  readonly matrixRow: string;
  readonly frozenBoundary: string;
};

export const G35_GOVERNANCE_MATRIX: readonly G35GovernanceRow[] = [
  { matrixRow: 'MERGED_IDENTITY_FOUR_PRIMARY_MEMBERS_PRESERVED_WITHOUT_ARTIFACT_OWNER_CONFLATION', frozenBoundary: 'MERGED_IDENTITY_FOUR_PRIMARY_MEMBERS_PRESERVED_WITHOUT_ARTIFACT_OWNER_CONFLATION' },
  { matrixRow: 'DETERMINISTIC_EXACT_REPLAY_INVIOLABLE_NO_EPSILON_TOLERANCE_ROUNDING_ALLOWANCE_OR_COMPENSATION', frozenBoundary: 'DETERMINISTIC_EXACT_REPLAY_INVIOLABLE_NO_EPSILON_TOLERANCE_ROUNDING_ALLOWANCE_OR_COMPENSATION' },
  { matrixRow: 'DETERMINISTIC_MISMATCH_REMAINS_SEVERITY_1_AND_BLOCKS_AFFECTED_RULE_VERSION', frozenBoundary: 'DETERMINISTIC_MISMATCH_REMAINS_SEVERITY_1_AND_BLOCKS_AFFECTED_RULE_VERSION' },
  { matrixRow: 'RECORDED_REPLAY_USES_EXACT_SAVED_NON_PERSONAL_RESPONSE_ARTIFACT_WITH_IMMUTABLE_PROVENANCE_AND_REMAINS_DISTINCT_FROM_BOUNDED_REPLAY', frozenBoundary: 'RECORDED_REPLAY_USES_EXACT_SAVED_NON_PERSONAL_RESPONSE_ARTIFACT_WITH_IMMUTABLE_PROVENANCE_AND_REMAINS_DISTINCT_FROM_BOUNDED_REPLAY' },
  { matrixRow: 'PROBABILISTIC_COMPONENT_REMAINS_ADVISORY_ONLY_WITHOUT_QUALIFICATION_GATE_AUTHORITY', frozenBoundary: 'PROBABILISTIC_COMPONENT_REMAINS_ADVISORY_ONLY_WITHOUT_QUALIFICATION_GATE_AUTHORITY' },
  { matrixRow: 'CLOSED_EXPLICIT_IMMUTABLE_VERSION_HASH_BOUND_FUTURE_CANDIDATE_DISCIPLINE', frozenBoundary: 'CLOSED_EXPLICIT_IMMUTABLE_VERSION_HASH_BOUND_FUTURE_CANDIDATE_DISCIPLINE' },
  { matrixRow: 'AFFECTED_USE_FAIL_CLOSED_WITHOUT_DEFAULT_PASS_NEGATIVE_FACT_ROUTE_OR_PRESENTATION_AUTHORITY', frozenBoundary: 'AFFECTED_USE_FAIL_CLOSED_WITHOUT_DEFAULT_PASS_NEGATIVE_FACT_ROUTE_OR_PRESENTATION_AUTHORITY' },
  { matrixRow: 'PER_COMPONENT_AND_REASON_INVARIANT_NON_COMPENSATION_AND_NO_MASKING', frozenBoundary: 'PER_COMPONENT_AND_REASON_INVARIANT_NON_COMPENSATION_AND_NO_MASKING' },
  { matrixRow: 'IMMUTABLE_FROZEN_PREREGISTERED_EVIDENCE_PREREQUISITES_DO_NOT_APPROVE_EXACT_CONTENT', frozenBoundary: 'IMMUTABLE_FROZEN_PREREGISTERED_EVIDENCE_PREREQUISITES_DO_NOT_APPROVE_EXACT_CONTENT' },
  { matrixRow: 'REPLAY_CREATES_NEW_AUDIT_EVENT_AND_NEVER_MUTATES_HISTORICAL_MATCH_RESULT', frozenBoundary: 'REPLAY_CREATES_NEW_AUDIT_EVENT_AND_NEVER_MUTATES_HISTORICAL_MATCH_RESULT' },
  { matrixRow: 'SYNTHETIC_OR_REPLAY_SUCCESS_CREATES_NO_PRODUCTION_POLICY_RUNTIME_OR_AUTOMATIC_ACTION', frozenBoundary: 'SYNTHETIC_OR_REPLAY_SUCCESS_CREATES_NO_PRODUCTION_POLICY_RUNTIME_OR_AUTOMATIC_ACTION' },
  { matrixRow: 'PARTIALLY_RESOLVED_BOUNDARY_EXACT_TOLERANCE_INVARIANT_DATA_POLICY_RUNTIME_CONTENT_OPEN', frozenBoundary: 'PARTIALLY_RESOLVED_BOUNDARY_EXACT_TOLERANCE_INVARIANT_DATA_POLICY_RUNTIME_CONTENT_OPEN' }
] as const;

export const G35_ROLE_SEPARATION = [
  'XFR-D-M4 GOVERNANCE OWNER: DEVELOPMENT + AI — HUMAN-APPROVED CANDIDATE-DERIVED AND NOT SOURCE_NORMATIVE',
  'EVALUATION PLAN ARTIFACT OWNER: AI + DEVELOPMENT',
  'RISK POLICY ARTIFACT OWNER: Chief AI Architect + LEGAL',
  'QUALIFICATION POLICY ARTIFACT OWNER: Chief AI Architect + PRODUCT',
  'SCORING POLICY ARTIFACT OWNER: Chief AI Architect + PRODUCT',
  'MANDATORY APPROVERS: Chief AI Architect + PRODUCT + LEGAL',
  'EVIDENCE/TECHNICAL-PROCEDURE OWNER: DEVELOPMENT + AI — NO UNILATERAL TOLERANCE, INVARIANT, POLICY, PRODUCTION, RUNTIME, RELEASE, IMPLEMENTATION OR GATE AUTHORITY',
  'ONE MERGED QUESTION DOES NOT MERGE ARTIFACT OWNERS, AND G35 ASSIGNS NO NEW OWNER OR WIDENS ANY AUTHORITY'
] as const;

export const G35_REPLAY_SEPARATION = [
  'DETERMINISTIC REPLAY REMAINS EXACT-ONLY: NO EPSILON, TOLERANCE, ROUNDING ALLOWANCE, MAJORITY MATCH, MASKING OR COMPENSATION APPLIES',
  'A DETERMINISTIC MISMATCH REMAINS SEVERITY-1 AND BLOCKS THE AFFECTED RULE VERSION',
  'RECORDED REPLAY USES THE EXACT SAVED NON-PERSONAL RESPONSE ARTIFACT WITH IMMUTABLE PROVENANCE; ITS SCHEMA, RETENTION, ACCESS, COMPATIBILITY AND LAWFUL HANDLING REMAIN OPEN',
  'RECORDED REPLAY AND BOUNDED PROBABILISTIC REPLAY REMAIN DISTINCT; SUCCESS IN ONE MODE DOES NOT SELECT, AUTHORIZE OR SUPPLY A BOUND FOR THE OTHER',
  'PROBABILISTIC OUTPUT REMAINS ADVISORY-ONLY AND CREATES NO ELIGIBILITY, RISK, QUALIFICATION, RANKING, ROUTING, PRESENTATION OR QUALIFICATION-GATE AUTHORITY',
  'REPLAY CREATES A NEW AUDIT EVENT AND NEVER MUTATES, REPLACES, RELABELS OR REINTERPRETS A HISTORICAL MATCH RESULT'
] as const;

export const G35_FAIL_CLOSED_AND_EVIDENCE = [
  'MISSING, UNKNOWN, STALE, EXPIRED, REVOKED, CONFLICTING, INCOMPLETE, CONTAMINATED, UNAUTHORIZED OR INCOMPATIBLE INPUT, ARTIFACT, PROVENANCE, VERSION/HASH, CONFIGURATION, CANDIDATE, INVARIANT OR EVIDENCE BLOCKS ONLY THE AFFECTED USE',
  'NO ZERO, EPSILON, NEAREST, AVERAGE, DEFAULT, PRIOR, MAJORITY, HEURISTIC OR AI-INFERRED SUBSTITUTE OR DEFAULT PASS IS CREATED',
  'FAILURE CREATES NO NEGATIVE BUSINESS FACT, HARD CONSTRAINT, INELIGIBLE RESULT, RISK OR QUALIFICATION ROUTE, REASON OR PRESENTATION AUTHORITY',
  'AGGREGATE CLOSENESS CANNOT HIDE AN OUT-OF-BOUND OR UNEVALUABLE COMPONENT; PASSING COMPONENTS, SLICES, METRICS OR RUNS CANNOT MASK MISSING OR ADVERSE EVIDENCE',
  'NUMERIC BOUNDS CANNOT COMPENSATE A VIOLATED REASON-CODE INVARIANT, AND INVARIANT PRESERVATION CANNOT COMPENSATE AN OUT-OF-BOUND NUMERIC RESULT',
  'IMMUTABLE FROZEN PREREGISTERED EVIDENCE CATEGORIES ARE PREREQUISITES, NOT APPROVAL OF ANY METHOD, VALUE, RESULT OR VERDICT',
  'SYNTHETIC OR REPLAY SUCCESS CREATES NO PRODUCTION CLAIM AND NO RESULT AUTOMATICALLY CHANGES POLICY, MODEL, SCORE, RANK, ROUTE, RELEASE, RUNTIME, MONITORING, ROLLBACK OR GATE'
] as const;

export const G35_OPEN_CONTENT = [
  'TOLERANCE VALUE, RANGE, UNIT, DIRECTION, COMPARATOR, INCLUSIVITY AND EDGE RULES',
  'ABSOLUTE, RELATIVE, DISTRIBUTIONAL, PER-COMPONENT, PER-OUTPUT AND AGGREGATE ERROR METRICS',
  'REASON-CODE INVARIANT CATALOG, NAMESPACE, VALUE, ORDER AND COMPATIBILITY RULES',
  'COMPONENT ELIGIBILITY, ADVISORY SCOPE AND RECORDED-VERSUS-BOUNDED SELECTION OR FALLBACK',
  'AGGREGATION, WEIGHTING, MASKING PREVENTION AND MULTI-COMPONENT TREATMENT',
  'RECORDED-ARTIFACT SCHEMA, PROVENANCE DETAILS, RETENTION, ACCESS, COMPATIBILITY AND LAWFUL HANDLING',
  'DATASET, SAMPLE ALLOCATION, SPLIT, SEED, LABELS, ADJUDICATION, CORRECTIONS AND FROZEN MANIFEST',
  'METRIC TARGET, UNCERTAINTY, INTERVAL, WINDOW, HYPOTHESIS TEST, STATISTIC, RESULT AND VERDICT',
  'REPRESENTATION, PRECISION, ROUNDING, SERIALIZATION AND NUMERIC EDGE BEHAVIOR',
  'POLICY, MANIFEST, PRODUCTION DATA, SCHEMA, CARRIER, API, DB, EVENTS, RUNTIME, MONITORING, ROLLBACK, MIGRATION, IMPLEMENTATION AND GATES'
] as const;

export const G35_PROHIBITED_SURROGATES = [
  'NO LIBRARY OR PLATFORM DEFAULT, EPSILON, ZERO, NEAREST, AVERAGE, PRIOR, MAJORITY, HEURISTIC OR AI INFERENCE MAY SUPPLY OPEN CONTENT',
  'AGGREGATE CLOSENESS, FAVORABLE BUSINESS OUTCOME, SYNTHETIC SUCCESS, CI SUCCESS OR CURRENT IMPLEMENTATION BEHAVIOR CANNOT SUBSTITUTE FOR OPEN AUTHORITY OR EVIDENCE',
  'XFR-D-020, XFR-D-023, XFR-D-026, XFR-D-027 AND XFR-D-057 THROUGH XFR-D-071 REMAIN INDEPENDENT AND SUPPLY NO TOLERANCE OR AUTOMATIC AUTHORITY'
] as const;

export const G35_NON_DECISION_RESULT =
  'G35 NON-DECISION RESULT: NO REPLAY TOLERANCE, RANGE, UNIT, ERROR METRIC, REASON-CODE INVARIANT, COMPONENT APPLICABILITY, MODE SELECTION OR FALLBACK, AGGREGATION, WEIGHTING, ARTIFACT SCHEMA, DATASET, STATISTIC, POLICY, MANIFEST, PRODUCTION-DATA USE, SCHEMA, CARRIER, API, DB, EVENT, RUNTIME, MONITORING, ROLLBACK, MIGRATION OR IMPLEMENTATION IS SELECTED, CALCULATED OR APPROVED. XFR-D-M4 v1.0 REMAINS PARTIALLY_RESOLVED_BOUNDARY; EP-10 + MRP-11 + MQP-15 + MSP-14 REMAIN PRIMARY_MERGED_MEMBER OF XFR-D-M4. SYNTHETIC OR REPLAY SUCCESS CREATES NO PRODUCTION CLAIM, GATE IMPACT IS NONE, AND ALL THREE GOVERNANCE GATES REMAIN BLOCKED.' as const;

export const G35_TERMINAL_TOKEN =
  'G35_SYNTHETIC_NO_REPLAY_TOLERANCE_ERROR_METRIC_REASON_INVARIANT_MODE_SELECTION_POLICY_PRODUCTION_OR_RUNTIME_USE_SELECTED' as const;

export const G35_TERMINAL_LINE =
  'NO REPLAY TOLERANCE, ERROR METRIC, REASON INVARIANT, MODE SELECTION, DATA, POLICY, PRODUCTION, RUNTIME OR IMPLEMENTATION ACTION OCCURRED' as const;
